### ISSUE TITLE
Not display image when tableview scroll fast

### ISSUE THREAD

**Issue by dfing** [rs/SDWebImage#1073] opened 2015-03-17 09:04 UTC
I have a tableview that include 1000 cells, each cell has a imageView.
In the `tableView:cellForRowAtIndexPath:` , I use `sd_setImageWithURL:placeholderImage:options:` for download the image from network. like that
```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
ItemTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"ItemCell" forIndexPath:indexPath];
        
        if ( cell == nil ) {
            cell = [[ItemTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"ItemCell"];
        }

        NSString *thumb_img = @"https://url";
        
        [cell.thumb_img sd_setImageWithURL:[NSURL URLWithString:thumb_img] placeholderImage:imageLoading options:SDWebImageHighPriority];

return cell;
}
```

If I scroll the tableview by **normal speed**, every imageView will display the image.
But, if I scroll it **very fast**, the imageView will **NOT** display the image, even I wait a while.

can everyone tell me how to do fix this issue?
Thanks!

**Comment by mythodeia** [comment] 2015-03-17 09:13
can this issue be replicated in the demo project as well?
you can try and change the queue mode using ```SDWebImageDownloaderQueueMode```
```
SDWebImageManager.sharedManager.imageDownloader.queueMode = SDWebImageDownloaderLIFOQueueMode;
```

**Comment by dfing** [comment] 2015-03-17 10:01
@mythodeia  I do not know how to copy better, but I will try...
I try to do your suggestion
I remove the `SDWebImageHighPriority ` , and run, I still get same problem.
And after I try to change the queue mode, add code like that
```
SDWebImageDownloader *imagedownloader = [SDWebImageDownloader sharedDownloader];
imagedownloader.executionOrder = SDWebImageDownloaderLIFOExecutionOrder;
```
I get same problem :(

Once this problem occurs, I select a row from tableview, and push to the next view
the imageview in next view also NOT display. 
why?

btw
At start, I think the last image has high Priority, so I use `SDWebImageHighPriority `, is wrong?

**Comment by mythodeia** [comment] 2015-03-17 10:14
the code you entered is correct. that should be added in the viewdidload.
however this should not be necessary since as you scroll the tableview the request for images that are not shown in view are cancelled and the new ones are added to the queue.
Does this happen on the example project as well? The example project has more than 100 images i think. can you try it there?
if the issue does not occur on the example project what you could do is share a demo project with this issue so we can debug it further.

**Comment by heistings** [comment] 2015-03-17 10:26
`Once this problem occurs, I select a row from tableview, and push to the next view
the imageview in next view also NOT display. 
why?`

It seems that the image download is still not finished. Since you use the `dequeueReusableCellWithIdentifier ` method, a cell may be called `sd_setImageWithURL` many times. I'm thinking of whether this issue can be reproduced by calling the `sd_setImageWithURL` of image view not on a cell.

**Comment by heistings** [comment] 2015-03-18 02:20
Oh, I can not reproduce this bug by calling` sd_setImageWithRUL` 1000 times.

**Comment by dfing** [comment] 2015-03-18 02:28
@mythodeia  @heistings  sorry, I reply late.
I was run the example project, and It seem to no occur the problem.
So I try to reproduce my bug in demo project, but I'm not finished.
I'm trying

**Comment by heistings** [comment] 2015-03-18 04:12
@dfing  Never mind :) waiting for your news.

**Comment by dfing** [comment] 2015-03-18 04:44
I try to reproduce the bug, you can clone demo project from my github
`https://github.com/dfing/myDemo`
It's only 264 items, and It occur the problem
when I scroll down the tableview **fast**, I will get the bug
Oh, I don't understand why :( 
please help me, thank you a lot!!!!!

**Comment by dfing** [comment] 2015-03-18 06:14
I add a few code at `viewWillDisappear:` , like that
```
-(void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:YES];
    SDWebImageManager *sharedManager = [SDWebImageManager sharedManager];
    [sharedManager cancelAll];
}
``` 
I think when I push the next view, I must to cancel all download task
so that I use `sd_setImageWithURL` in `DetailViewController.m` of myDemo, I think It will work.
But, I seem to be thinking wrong, because the imageView in DetailViewController also NO reaction.

When I return tableview, I log `currentDownloadCount`, I get 0 download.
I scroll the tableview, It will start downloading the image again, right?
But the imageView no more display image.
mn..Is this thread blocking??

**Comment by mythodeia** [comment] 2015-03-18 06:57
first of all when you use this:
```
DemoTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"ItemCell" forIndexPath:indexPath];
```
i think you do not need to add this:
```
    if (cell == nil) {
        cell = [[DemoTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"ItemCell"];
    }
```
it takes care that for you!
also remove this:
```
 SDWebImageManager.sharedManager.imageDownloader.executionOrder = SDWebImageDownloaderLIFOExecutionOrder;
```
i tried with those changes on device and simulator and despite some 404 links everything else is working fine. no problems at all. Of course sometimes the amazon S3 from previous experience takes some time to return the images from your request.

**Comment by heistings** [comment] 2015-03-18 07:05
Oh, you have to remote the codes:

```
    SDWebImageManager *sharedManager = [SDWebImageManager sharedManager];
    [sharedManager cancelAll];
```

Because every time you push the detail, the requests are canceled.

**Comment by mythodeia** [comment] 2015-03-18 07:06
@heistings on the demo that code is not included anywhere

**Comment by heistings** [comment] 2015-03-18 07:08
@mythodeia in `viewWillDisappear`

```objective-c
-(void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:YES];
    SDWebImageManager *sharedManager = [SDWebImageManager sharedManager];
    [sharedManager cancelAll];
}
```

**Comment by mythodeia** [comment] 2015-03-18 07:09
thats very weird....i do not have this piece of code in my download from https://github.com/dfing/myDemo

**Comment by heistings** [comment] 2015-03-18 07:10
In the ViewController class.

**Comment by mythodeia** [comment] 2015-03-18 07:12
nope...i cloned the git and the viewcontroller does not have it there....so weird...

**Comment by heistings** [comment] 2015-03-18 07:13
I just removed the codes, and the demo works fine for me:

```
//    SDWebImageManager.sharedManager.imageDownloader.executionOrder = SDWebImageDownloaderLIFOExecutionOrder;
```

```
-(void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:YES];
//    SDWebImageManager *sharedManager = [SDWebImageManager sharedManager];
//    [sharedManager cancelAll];
}
```

```
- (void)flushCache
{
//    [SDWebImageManager.sharedManager.imageCache clearMemory];
//    [SDWebImageManager.sharedManager.imageCache clearDisk];
    NSLog(@"flushCache");
}
```

**Comment by mythodeia** [comment] 2015-03-18 07:14
aha! i just saw that when i downloaded the code the commit https://github.com/dfing/myDemo/commit/23d3af646e4b6fee1a925e65282ce3d5f1eb747b 
was not introduced. so thats why it was working for me

**Comment by heistings** [comment] 2015-03-18 07:14
I think there is no need to set SDWebImageManager.sharedManager when you are only using methods like `sd_setImageWithURL`.

**Comment by dfing** [comment] 2015-03-18 07:14
@mythodeia  I don't understand why I do not need to add:
```
if (cell == nil) {
        cell = [[DemoTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"ItemCell"];
    }
```
Is it not for **UITableViewCell reuse** ??

I also think about server return time, but sometimes I found even download comeback, it still not display image. 
(I log currentDownloadCount, when It start downloading that count is 6, after finished count become 0 )

**Comment by mythodeia** [comment] 2015-03-18 07:15
@dfing check this
http://stackoverflow.com/questions/25826383/when-to-use-dequeuereusablecellwithidentifier-vs-dequeuereusablecellwithidentifi

**Comment by heistings** [comment] 2015-03-18 07:21
Seems there is no bug with SDWebImage?

**Comment by mythodeia** [comment] 2015-03-18 07:23
for me its working fine...i cant seem to make it work like @heistings suggested. Did you?

**Comment by heistings** [comment] 2015-03-18 07:27
I met the error below, about image not displayed:
`url : https://s3.buy123.com.tw/images/item/46AAHRK_retina.png : error : Error Domain=NSURLErrorDomain Code=-1100 "The operation couldn’t be completed. (NSURLErrorDomain error -1100.)"`

And I can not open the url with chrome.

**Comment by dfing** [comment] 2015-03-18 07:30
@heistings  a few retina.png are not exist.

**Comment by heistings** [comment] 2015-03-18 07:32
@dfing So there is no bug with SDWebImage, is there?

**Comment by mythodeia** [comment] 2015-03-18 07:33
@dfing please try with our suggestions and let us know if there is any other issue so we can close this :)

**Comment by dfing** [comment] 2015-03-18 07:37
I remove the code:
```
if (cell == nil) {
        cell = [[DemoTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"ItemCell"];
    }
```
and 
```
SDWebImageManager *sharedManager = [SDWebImageManager sharedManager];
    [sharedManager cancelAll];
```
and
```
SDWebImageManager.sharedManager.imageDownloader.executionOrder = SDWebImageDownloaderLIFOExecutionOrder;
```
but somethings it still not display image even the `currentDownloadCount` is 0.

**Comment by heistings** [comment] 2015-03-18 07:39
You can select the cell, and waiting for the complete block to see what happened with the url
```
    [self.detailImg sd_setImageWithURL:[NSURL URLWithString:retina_url]
                       placeholderImage:imageLoading
                              completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL){
                                  NSLog(@"url : %@ : error : %@", imageURL, error);
                                  if (error != nil) {
                                      [self.detailImg sd_setImageWithURL:[NSURL URLWithString:main_url] placeholderImage:imageLoading];
                                  }
                              }];
```

**Comment by heistings** [comment] 2015-03-18 07:43
Or you can set a load failed image for cells who's url connection could not be finished successfully:

```
    __weak __typeof(cell) weakCell = cell;
    [cell.imageView sd_setImageWithURL:[NSURL URLWithString:url] placeholderImage:imageLoading completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        weakCell.imageView.image = [UIImage imageNamed:@"LoadFailedImage"];
    }];
```

**Comment by mythodeia** [comment] 2015-03-18 07:44
take into consideration that sometimes the s3 does not respond immediately

**Comment by heistings** [comment] 2015-03-18 07:45
@dfing I think @mythodeia has gotten the point.

**Comment by dfing** [comment] 2015-03-18 07:52
@mythodeia  @heistings  I think seem to no bug with SDWebImage, I will think about that if it is the s3 problems. Thank you two, you help me a lot!!  Thanks again!!

**Comment by mythodeia** [comment] 2015-03-18 07:54
good luck with your app
@heistings thanks :+1:

**Closed by mythodeia** 2015-03-18 07:54 UTC

**Comment by heistings** [comment] 2015-03-18 07:55
Pleasure with all you guys. :) And you can close this issue.
