### ISSUE TITLE
Offline (AirPlan Mode ) not Clear Cache

### ISSUE THREAD

**Issue by AmeerChand** [rs/SDWebImage#2411] opened 2018-07-31 10:18 UTC
my Device was online i download all images
it's work fine
but the issue is with offline (airplane mode) Cache Clearing.
i am using the below code to clear Cache.but not working.
it show's me the actual cache  size on disk
after clear memory and clear disk
it show me 0 size.
but not clear the cache.my device is still offline (AirPlan Mode) 
i am scrolling the TableViewCellImage it's show all image while i already Clear the Cache in offline mode.

        print("The size on disk is =", SDImageCache.shared().getSize())
        SDImageCache.shared().clearMemory()
        SDImageCache.shared().clearDisk()
        print("The size on disk is =", SDImageCache.shared().getSize())

above code output is 
The size on disk is = 5310705
The size on disk is = 0
but not Clear the Cache?
what to do to Clear the Cache in offline (airplane mode)

**Comment by bpoplauschi** [comment] 2018-07-31 14:36
This is duplicate of #2410

**Closed by bpoplauschi** 2018-07-31 14:36 UTC
