### ISSUE TITLE
sometime download image will success, sometime will fail

### ISSUE THREAD

**Issue by g001613001** [rs/SDWebImage#1813] opened 2017-02-18 04:12 UTC
i'm use swift 
#import "SDWebImage/UIImageView+WebCache.h"
and i just use this:
imageView.sd_setImage(with: URL(string: imgUrl))

sometime i'm try to show image, it will success.
but sometime will fail, and it will never to success download image.

even i rerun project, or remove app rerun.

i'm don't know why?

and how to fix this issue?

**Comment by skyline75489** [comment] 2017-02-18 06:43
Is there any error information that you can provide?

**Comment by bpoplauschi** [comment] 2017-02-19 12:45
@g001613001 please fill in the information required in the [ISSUE TEMPLATE](https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md).

It's relevant that we know which version of the library are you using, if you can share the image url, if it reproduces constantly or not, if you can reproduce it with our demo, if you have a demo project where the issue is constantly reproducing.

@mythodeia @skyline75489 Retorical question: why do people keep ignoring the issue template when creating an issue?

**Comment by g001613001** [comment] 2017-02-20 02:33
@bpoplauschi
Platform Name	ios 
Platform Version	 8.1/ 9.0/ 10.1 
SDWebImage Version	3.8.2
Integration Method	 cocoapods
Xcode Version	Xcode 8.2.1
Repro rate	sometimes when fail will never success
Repro with our demo prj	demo project can't run.
Demo project link	(Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://itvcloud.org/KFAAppService/MAM/Thumbnail/Promo/Home/31298515-29f8-4f7a-a422-252afb5d5470.png, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://itvcloud.org/KFAAppService/MAM/Thumbnail/Promo/Home/31298515-29f8-4f7a-a422-252afb5d5470.png})

sorry for late reply.

**Comment by bpoplauschi** [comment] 2017-02-20 06:15
@g001613001 I cannot access this image URL: https://itvcloud.org/KFAAppService/MAM/Thumbnail/Promo/Home/31298515-29f8-4f7a-a422-252afb5d5470.png
Make sure your server is accessible all the time and provides the image. 
I don't think this is an issue with our library.
Closing the ticket. Will reopen if new info arrises.

**Closed by bpoplauschi** 2017-02-20 06:15 UTC

**Comment by g001613001** [comment] 2017-02-20 06:33
I think it is server SSL proplem.
so I use allowInvalidSSLCertificates.
It's not working too.
BTW, Kingfisher this lib can work for download image success.
I don't know why?

**Comment by bpoplauschi** [comment] 2017-02-20 07:07
Indeed, something is strange with the server, because I cannot access the image from my browser.
