### ISSUE TITLE
Crash: SDWebImageDownloaderOperation.m line 85 

### ISSUE THREAD

**Issue by xhzth7091** [rs/SDWebImage#1988] opened 2017-08-07 09:35 UTC
SDWebImage Version | 4.0.0
-- | --
Integration Method | cocoapods /
Xcode Version | Xcode 8.2.1

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x19489bbdc objc_msgSend + 28
1  CoreFoundation                 0x182f41458 CFRelease + 524
2  CFNetwork                      0x182999f38 HTTPRequestParserClient::~HTTPRequestParserClient() + 52
3  CFNetwork                      0x182999ef4 HTTPRequestMessage::~HTTPRequestMessage() + 80
4  CoreFoundation                 0x182f41394 CFRelease + 328
5  CFNetwork                      0x18299a144 URLRequest::~URLRequest() + 152
6  CoreFoundation                 0x182f41394 CFRelease + 328
7  CFNetwork                      0x182aa9e68 -[NSURLRequestInternal dealloc] + 40
8  CFNetwork                      0x182aab124 -[NSURLRequest dealloc] + 48
9  libobjc.A.dylib                0x194886b1c object_cxxDestructFromClass(objc_object*, objc_class*) + 148
10 libobjc.A.dylib                0x194893f38 objc_destructInstance + 92
11 libobjc.A.dylib                0x194893f90 object_dispose + 28
12 Foundation                     0x183e96b14 -[NSOperation dealloc] + 104
13 ??????                         0x1008ae4fc -[SDWebImageDownloaderOperation dealloc] (SDWebImageDownloaderOperation.m:85)
14 libsystem_blocks.dylib         0x194f31910 _Block_release + 256
15 libdispatch.dylib              0x194ed9954 _dispatch_client_callout + 16
16 libdispatch.dylib              0x194ede20c _dispatch_main_queue_callback_4CF + 1608
17 CoreFoundation                 0x18301b7f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x1830198a0 __CFRunLoopRun + 1492
19 CoreFoundation                 0x182f452d4 CFRunLoopRunSpecific + 396
20 GraphicsServices               0x18c75b6fc GSEventRunModal + 168
21 UIKit                          0x187b0afac UIApplicationMain + 1488
22 ??????                         0x100144178 main (main.m:14)
23 libdyld.dylib                  0x194f06a08 start + 4

**Comment by bpoplauschi** [comment] 2017-08-08 09:56
@xhzth7091 this is a duplicate of #1859 - that is why the template asks you to search for issues before opening a new one.
Please add to that thread - we released a fix in version 4.1.0, but let us know if that doesn't resolve it for you.

**Closed by bpoplauschi** 2017-08-08 09:56 UTC
