### ISSUE TITLE
Crash in sd_imageOrientationFromImageData

### ISSUE THREAD

**Issue by dbrockman** [rs/SDWebImage#919] opened 2014-10-02 15:10 UTC
- Version 3.7.1
- Might be related to #813

An exception is thrown in `CGImageSourceCopyPropertiesAtIndex` in `sd_imageOrientationFromImageData`.
The error message is: `<Error>: ImageIO: CreateMetadataFromXMPBufferInternal  Threw error #201 (XML parsing failure)`

**Comment by schwers** [comment] 2015-01-27 18:01
@bpoplauschi have you had a chance to look into this?

**Comment by endrelovas** [comment] 2015-03-30 18:09
Same issue here. Any progress?

**Comment by houmie** [comment] 2015-06-30 11:52
I get the same error message with these two images.  I didn't have this problem a week ago, was there any recent update that might have caused it?  Out of 120 images, 20 fail like this.

http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/6/29/1435601959164/THouses-of-Parliament-009.jpg?w=300&q=85&auto=format&sharp=10&s=66a23b573e9f018b26c3abb705f3792d

and

http://i.guim.co.uk/img/media/d126680aca92ff4251536f788b60233b5463af89/1585_707_3685_2210/3685.jpg?w=300&q=85&auto=format&sharp=10&s=5e00d99e290864557620bf175b873462

**Comment by mythodeia** [comment] 2015-07-02 09:39
the warning appears when this fires:
CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);
i cannot guess what Apple might be doing under the hood but its whats causing the issue. Since its a warning and not a crash i think you are ok. 
I will close this as this is not something SDWebImage is responsible for or able to fix any other way.

If by any chance anyone finds another way please let us know
you can find an image [here](https://github.com/rs/SDWebImage/issues/943#issuecomment-117912695)

**Closed by mythodeia** 2015-07-02 09:39 UTC
Labels: crash

**Comment by houmie** [comment] 2015-07-02 21:24
Well the problem is SDWebImage not showing these images, instead the alternate image is shown. 
Other images are shown, so its clearly it has something to do with SDWebImage.

Here is another example, it works in web browser but not with SDWebimage lib:
http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/2/1435859710434/Smoke-rises-in-the-Syrian-009.jpg?w=645&q=85&auto=format&sharp=10&s=d2fc39fb6c896312e9c02a238871a7ba

Any advice please?

**Comment by houmie** [comment] 2015-07-02 21:30
I think I know what it might cause it.

Check out the url above, it seems SDWebimage only reads everything up to *.jpg and everything after is ignored.  Try to do that in webbrowser:

http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/2/1435859710434/Smoke-rises-in-the-Syrian-009.jpg

And you get a ```Not authorized```.   This must be the reason why all these type of images are being ignored by SDWebImage, is there anything that can be done please?

**Comment by mythodeia** [comment] 2015-07-03 05:24
@houmie [this](http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/2/1435859710434/Smoke-rises-in-the-Syrian-009.jpg?w=645&q=85&auto=format&sharp=10&s=d2fc39fb6c896312e9c02a238871a7ba) image shows just fine when i tried it in the demo project.
[this url](http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/2/1435859710434/Smoke-rises-in-the-Syrian-009.jpg) is not loaded at all just like in the webbrowser

**Comment by houmie** [comment] 2015-07-03 07:45
@mythodeia this is strange.  I try to load them like this:

```
[_newsImage sd_setImageWithURL:imageURL placeholderImage:[UIImage imageNamed:alternative_image_name]];
```

I always get the alternative image shown. But only for the links I provided above such as <a href="http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/2/1435859710434/Smoke-rises-in-the-Syrian-009.jpg?w=645&q=85&auto=format&sharp=10&s=d2fc39fb6c896312e9c02a238871a7ba">this</a>.
normal image urls without all those parameters after *.jpg are working fine.

To handle these problematic urls better, I just switched to <a href="https://github.com/Haneke/Haneke">Haneke</a> and used this instead:
```
[_newsImage hnk_setImageFromURL:imageURL];
```

And guess what it works!  Hence it must be a bug with SDWebImage.

**Comment by mythodeia** [comment] 2015-07-03 07:53
can you try the url with the parameters in the demo project? remove all other urls and leave only the [this](http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/2/1435859710434/Smoke-rises-in-the-Syrian-009.jpg?w=645&q=85&auto=format&sharp=10&s=d2fc39fb6c896312e9c02a238871a7ba)

if you see the demo project it uses the code below to load the image in a tableviewcell:
```
    [cell.imageView sd_setImageWithURL:[NSURL URLWithString:[_objects objectAtIndex:indexPath.row]]
                      placeholderImage:[UIImage imageNamed:@"placeholder"]
                               options:0];
```
The proper image loads just fine.

**Comment by houmie** [comment] 2015-07-03 21:09
@mythodeia I really appreciate your help on this.  I have been now working on this for hours without any step forwards.  I would like to keep SDWebImage since Haneke doesn't seem to support prefetching.

Yes I have used the demo with that URL and it works, but it doesn't work in my app and I am so frustrated. I was wondering if this particular img provider has been blocked because of previous failures. Could it be?

So I set the options like this:
```
    [_newsImage sd_setImageWithURL:imageURL placeholderImage:[UIImage imageNamed:alternative_image_name] options:(SDWebImageProgressiveDownload | SDWebImageRetryFailed)];  
```

But still no joy.  Then I tried to to enable the verbose to get a message what is happening.
In AppDelegate.m I have set it like this, I'm not sure if this is the right way:
```
define SD_VERBOSE
```

But I don't see anything verbose when this line is loading:

```
[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:images];
```

But I can already see that some are passing and some are failing:
```
2015-07-03 21:55:51.916 news[15844:373605] Prefetched 203 out of 277
2015-07-03 21:55:51.921 news[15844:373605] Prefetched 204 out of 277
2015-07-03 21:55:51.934 news[15844:373605] Prefetched 205 out of 277 (Failed)
2015-07-03 21:55:51.942 news[15844:373605] Prefetched 206 out of 277 (Failed)
```
The ones with urls beginning with these kind of url <a href="http://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/7/3/1435953204044/3bd04b62-ae57-4984-9041-c6a95409133c-2060x1236.jpeg?w=645&q=85&auto=format&sharp=10&s=d7185b074b2a5ffa8a843b45014af847">fail</a> and these ones always <a href="http://telegraph.feedsportal.com/c/32726/f/568301/s/47d1d249/sc/3/l/0L0Stelegraph0O0Cnews0Cworldnews0Cislamic0Estate0C117174270CWhat0Enext0Efor0Ethe0Emissing0EBethnal0EGreen0Egirls0Ein0ESyria0Bhtml/story01.htm">pass</a>. I don't know why the former ones always fail and latter always pass.

**Comment by mythodeia** [comment] 2015-07-03 22:32
The Verbose macro works with the prefetcher only and this outputs the logs ```Prefetched x out of x``` in the console.
as far as the url that is failing for you did you try to uninstall the app and retry? 
maybe the url was added to the failedUrl array.

**Comment by houmie** [comment] 2015-07-03 22:57
Yes, I have deleted the app from simulator, cleaned the build folder, deleted the pods and reinstalled version 3.7.0 and its still the same problem. I don't understand.  Is there a way to make sure no url is ever blocked no matter how often it had failed?

**Comment by mythodeia** [comment] 2015-07-04 05:57
the current version is 3.7.2
check [this comment](https://github.com/rs/SDWebImage/issues/1091#issuecomment-90866296) to override failedUrls array

**Comment by houmie** [comment] 2015-07-04 10:15
@mythodeia I found the bug and here is the proof: (v 3.7.2)

Checkout ```SDWebImageManager.m``` and set a breakpoint on the line 183.
See screenshot 1: (The telegraph <a href="http://i.telegraph.co.uk/multimedia/archive/03363/bluenotesymbol_3363885b.jpg">url</a> is able to get a ```downloadedImage``` instance, which is great !

<img width="635" alt="screen shot 2015-07-04 at 11 08 21" src="https://cloud.githubusercontent.com/assets/1832933/8507488/40624fb8-223d-11e5-87af-b46879c1d66d.png">

But with guardian <a href="http://i.guim.co.uk/img/media/22e3bdb76e11eafa92b3d6abc676ea9e515e643b/0_269_4256_2556/master/4256.jpg?w=645&q=85&auto=format&sharp=10&s=af23d29efa6e0194a41607ba25631aa0">url</a> the ```downloadedImage``` is nil (!)

<img width="642" alt="screen shot 2015-07-04 at 11 11 02" src="https://cloud.githubusercontent.com/assets/1832933/8507498/b90f425e-223d-11e5-96a8-a72b32bf2e18.png">

You see I wasnt crazy. There is a bug in your code, I just can't pinpoint exactly what is going on.  :)

**Comment by houmie** [comment] 2015-07-04 10:19
Speaking of which, the NSError for the failed guardian image says this:
```
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo=0x7fe1a1d836b0 {NSUnderlyingError=0x7fe1a403c420 "The request timed out.", NSErrorFailingURLStringKey=http://i.guim.co.uk/img/media/22e3bdb76e11eafa92b3d6abc676ea9e515e643b/0_269_4256_2556/master/4256.jpg?w=645&q=85&auto=format&sharp=10&s=af23d29efa6e0194a41607ba25631aa0, NSErrorFailingURLKey=http://i.guim.co.uk/img/media/22e3bdb76e11eafa92b3d6abc676ea9e515e643b/0_269_4256_2556/master/4256.jpg?w=645&q=85&auto=format&sharp=10&s=af23d29efa6e0194a41607ba25631aa0, NSLocalizedDescription=The request timed out.}
```
There you go, and the same image works fine with Haneke. So it must be somehow how SDWebImage handles this sort of encrypted urls.

**Comment by mythodeia** [comment] 2015-07-04 10:21
If you check the error you will see it's because of a timeout in your
internet connection.

**Comment by houmie** [comment] 2015-07-04 10:23
Internet connection is fine. I have 40 images, 20 from guardian and 20 from Telegraph.  The internet happens to disconnect for all guardians and remain stable for all telegraphs? c'mon. lol

**Comment by mythodeia** [comment] 2015-07-04 10:25
Read the error message carefully. Request timeout means that you could not
get a response from the server hosting the image. Google it

**Comment by mythodeia** [comment] 2015-07-04 10:25
I will check it when in a bit

**Comment by mythodeia** [comment] 2015-07-04 10:35
@houmie i added both urls in the demo project and both load just fine.
proof:
![screen shot 2015-07-04 at 1 34 53 pm](https://cloud.githubusercontent.com/assets/1748458/8507559/7ae09a0a-2251-11e5-985b-079d277fd2e7.png)

**Comment by houmie** [comment] 2015-07-04 10:37
I'm going to bang my head against the wall.  Thanks for your help though.. :-/

**Comment by mythodeia** [comment] 2015-07-04 10:42
when you add a breakpoint after the request is started the you will get 'request time out' because you are not letting the code continue. So the server will respond with a request time out (the error you posted above). So be careful with your breakpoints.

I really cannot understand why you are getting this issue when both urls you mentioned work just fine in the demo project. Please check your code again for anything you might have missed. Cell reusability issues, timeouts, etc...

**Comment by houmie** [comment] 2015-07-04 11:03
@mythodeia hey you are the star.  You were right, due taking screenshots I was waiting for too long in the breakpoint and reported a red herring.

I just did it again and got the real NSError for the given Guardian image.

```
Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo=0x7ff3741379f0 {NSLocalizedDescription=Downloaded image has 0 pixels}
```
There you go, I hope this helps nailing the problem.

**Comment by mythodeia** [comment] 2015-07-04 11:08
that error means that the downloaded image's size is zero. Are you sure you are not changing the url at all? the [guardian](http://i.guim.co.uk/img/media/22e3bdb76e11eafa92b3d6abc676ea9e515e643b/0_269_4256_2556/master/4256.jpg?w=645&q=85&auto=format&sharp=10&s=af23d29efa6e0194a41607ba25631aa0) needs to be exactly as it is or else you will get a not authorized error (even in the browser).

Please check both urls in the demo project. If both work then you need to readjust the code in your project as something there is causing your issues. Also make sure you are using the latest code from this lib.

just tried again with both urls and both work just fine

**Comment by houmie** [comment] 2015-07-15 10:57
yeah I'm 100% sure the url is not changing. Because when i use Haneke instead of SDWebimage, it works.  But Haneke is much slower than SDWebimage. :(

Could this problem be related to this: http://stackoverflow.com/a/21312221/92153

**Comment by mythodeia** [comment] 2015-07-15 13:31
@houmie if the urls you provided work on the demo app then there must be something wrong with your project. In another post you stated that the urls work in the demo app, right?

**Comment by dreampiggy** [comment] 2017-11-01 03:17
For user who still face this problem. Unset your exception breakpoints with that `__cxa_throw` and only keep `objc_exception`. This C++ exception will handlered by Image/IO framework and this will not cause any problem. Just a error log will print.
