### ISSUE TITLE
Simply cannot load this url: "https://http2.golang.org/file/gopher.png"

### ISSUE THREAD

**Issue by zhujinlong** [rs/SDWebImage#1560] opened 2016-05-16 07:15 UTC
Simply cannot load this url: "https://http2.golang.org/file/gopher.png"

import UIKit
import SDWebImage

class ViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let uiAvatar = UIImageView()
        uiAvatar.frame = CGRectMake(100, 100, 100, 100)
        self.view.addSubview(uiAvatar)
        
        let url = "https://http2.golang.org/file/gopher.png"
        
        uiAvatar.sd_setImageWithURL(NSURL(string: url)!, placeholderImage: nil, options: .AllowInvalidSSLCertificates)
    }
    

}

**Comment by bpoplauschi** [comment] 2016-05-29 12:46
There is something wrong with this image or at least unusual.
The root cause is `[[UIImage alloc] initWithData:data]` will return nil for this image. So the iOS UIImage class doesn't support it. After looking at some details, I observed this is a non-standard PNG, as the first byte should be 0x89, but it's 0x3C.

I don't think there is much we can do here. Closing the issue.

**Closed by bpoplauschi** 2016-05-29 12:46 UTC

**Comment by zhujinlong** [comment] 2016-05-30 08:57
The image is ok, if you save it to local and load it, it will show.

```
class ViewController: UIViewController {

	override func viewDidLoad() {
	    super.viewDidLoad()

	    let uiAvatar = UIImageView()
	    uiAvatar.frame = CGRectMake(100, 100, 100, 100)
	    self.view.addSubview(uiAvatar)

	    uiAvatar.image = UIImage(named: "gopher")
	}
	
}
```


And finally I found the reason, this url uses http2 protocol, but http2 is only supported by NSURLSession since iOS 9.

http://stackoverflow.com/questions/31238354/nsurlconnection-on-ios-9-does-not-use-http-2-protocol

**Comment by bpoplauschi** [comment] 2016-05-30 10:53
Strange. I have saved the image locally and it didn't work for me. As for the http2 protocol, I will replace our `NSURLConnection` code with `NSURLSession` in the 4.0 version, so it should work after that.
