### ISSUE TITLE
sd_setImageWithURL: completed:  completion block not called

### ISSUE THREAD

**Issue by ningliuliu** [rs/SDWebImage#1455] opened 2016-02-02 06:36 UTC
When I call sd_setImageWithURL: completed: very quickly,
 the completion block not called .
The following code：
`
[sdImageView sd_setImageWithURL:[NSURL URLWithString:self.artworkUri] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                    if(image == nil)
                    {
                    }
                    else
                    {
                        self.artwork = image;
                    }
                }];
`

**Comment by mythodeia** [comment] 2016-02-02 06:40
@ningliuliu what do you mean by calling that method very quickly?
can you reproduce in the sample project?

**Comment by bpoplauschi** [comment] 2016-05-29 19:00
Closing due to missing info.

**Closed by bpoplauschi** 2016-05-29 19:00 UTC

**Comment by bkvirendra** [comment] 2016-08-25 17:02
@bpoplauschi Hi I'm having the same issue and I am able to reproduce it.

**Comment by bkvirendra** [comment] 2016-08-25 17:05
So the scenario is, when i minimise the app and reopen it, and try to reload the same image (since the image is cached) it should be coming from the cache, but the success block does not get fired. Following the code snippet

    `[self.imageView sd_setImageWithURL:self.rewardList.rewardImage placeholderImage:nil options:SDWebImageHighPriority completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        [self initialiseParallaxHeaderWithImage:self.imageView.image forHeight:imageHeight];
    }];`

**Comment by bpoplauschi** [comment] 2016-08-26 20:03
@bkvirendra you'll have to debug inside the library code and see why the completion is not called

**Comment by bkvirendra** [comment] 2016-08-26 20:24
@bpoplauschi I resolved the issue by debugging inside the library, I wrote a small patch that worked for me, since I do some processing of the image once its loaded

`
    SDImageCache *cache = [SDImageCache sharedImageCache];
    UIImage *inMemoryImage = [cache imageFromMemoryCacheForKey:[self.rewardList.rewardImage absoluteString]];
    
    // resolves the SDWebImage issue of image missing
    if (inMemoryImage)
    {
        [self initialiseParallaxHeaderWithImage:inMemoryImage forHeight:imageHeight];
    }
    else if ([[SDWebImageManager sharedManager] diskImageExistsForURL:self.rewardList.rewardImage])
    {
        UIImage *image = [cache imageFromDiskCacheForKey:[self.rewardList.rewardImage absoluteString]];
        [self initialiseParallaxHeaderWithImage:image forHeight:imageHeight];
    }
    else
    {
        [self.rewardImageView sd_setImageWithURL:self.rewardList.rewardImage placeholderImage:nil options:SDWebImageHighPriority completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            [self initialiseParallaxHeaderWithImage:self.rewardImageView.image forHeight:imageHeight];
        }];
    }
`
