### ISSUE TITLE
Problem about decodedImageWithImage:

### ISSUE THREAD

**Issue by huoyi2000** [rs/SDWebImage#1186] opened 2015-06-18 07:37 UTC
The method named “decodedImageWithImage:” in SDWebimageDecoder caused my app to crash. When i use Instruments to check memory, i found a large image with size 5000*4000 lead the memory increase 60M+ and will never be released,some developers said that it may be because of NSCache.This may be a serious problem.If the image is very large or there are a lot of images.May occupy too much memory and lead the app run slower and slower until crash.

**Comment by mythodeia** [comment] 2015-06-18 08:24
i will close this one to avoid clutter. you can search with ```decodedImageWithImage``` for any open issues if you want. Try with the newest build and check the:
```shouldDecompressImages``` property of the ```SDImageCace``` & ```SDWebImageDownloaderOperation```
 
also read [this](https://github.com/rs/SDWebImage/issues/1072)

**Closed by mythodeia** 2015-06-18 08:24 UTC

**Comment by huoyi2000** [comment] 2015-06-27 06:13
I’m sorry for my wrong issue.I finally found it’s because my TableviewCell contains different number of images,so when i create a Cell,i remove all the imageViews first and then create new imageViews whose url is the same with the previous one.At last,I found a lot of imageViews has been download although they are with the same url.This happens only for big image(>3M).You can have a try.Can you ensure when a imageView is loading a image with a url,then another imageView with the same url needn’t load image with this url again?

**Comment by mythodeia** [comment] 2015-06-27 06:35
@huoyi2000 why are you removing the imageviews and recreating them? and why do you download >3MB images on your tableview? in my opinion its wrong. download smaller thumbs and load the bigger ones when the user asks for them. Anyway...by design now SDWebImage cancels any request if another one with the same url occurs. We know of this issue, thanks

**Comment by huoyi2000** [comment] 2015-06-27 07:04
I have to design a page like Twitter,each cell contains different number of photos,i write the cellForRowAtIndexPath method like this.
- (UITableViewCell *)tableview:(UITableView *)tableview cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
     static NSString *identifier = @“cell”;
    UITableViewCell *cell = [tableView dequenceReusableCellWithIdentifier: identifier];
   if(cell == nil)
   {
   cell =[ [UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:idendifier];
  }
 //remove all subviews to avoid duplication
  for(UIView *v in cell.contentView.subviews) {[v removeFromSuperView];};
  for(int i = 0;i < imageNum;i++)
{//create imageViews…};
return cell;
}
As for the image bigger than 3MB, it’s because our background designer didn’t notice it.
Maybe i didn’t download the latest version,so i find a url loaded more than once.Thanks.
