### ISSUE TITLE
Updated to 4.0 after the get method USES the image download progress.

### ISSUE THREAD

**Issue by LanYanQin** [rs/SDWebImage#1783] opened 2017-02-04 08:35 UTC
[imageView sd_setImageWithURL:imageUrl
                         placeholderImage:image
                                  options:SDWebImageAvoidAutoSetImage | SDWebImageRefreshCached
                                 progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL *targetURL) {
                                     
                NSNumber *rectivdNumber = [NSNumber numberWithInteger:receivedSize];
                CGFloat received = rectivdNumber.floatValue;
                
                NSNumber *expectedNumber = [NSNumber numberWithInteger:expectedSize];
                CGFloat expected = expectedNumber.floatValue;
                
                if (expectedSize != -1 && receivedSize != 0) {
                    rotateScaleView.progressView.progress = received / expected;
                }
            } completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
                if (image) {
                    imageView.image = image;
                }
                if (error != NULL) {
                    [rotateScaleView.progressView removeFromSuperview];
                }

            }];

**Here get photo download progress will lead to program crashes.**

       [imageView sd_setImageWithURL:imageUrl
                         placeholderImage:image
                                  options:SDWebImageAvoidAutoSetImage | SDWebImageRefreshCached
                                 progress:nil completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
                if (image) {
                    imageView.image = image;
                }
                if (error != NULL) {
                    [rotateScaleView.progressView removeFromSuperview];
                }

            }];

**Here the progress is set to nil, there is no problem.Excuse me what reason be?In previous versions have not found this problem.**

**Comment by skyline75489** [comment] 2017-02-04 12:18
What is the crash exactly

**Comment by LanYanQin** [comment] 2017-02-06 06:11
I use this on the simulator download image method is ok, but I'm really on board with this method will cause the program card dead flash back.
If I set SDWebImageDownloaderProgressBlock nil, there is no problem.

**Comment by bpoplauschi** [comment] 2017-02-06 06:45
@LanYanQin can you reproduce this crash with our demo project? Could you create a demo project of your own where this crash happens all the time? It would help identify the issue.
Also, what's the stack trace for the crash?

**Comment by LanYanQin** [comment] 2017-02-06 07:20
![9992ec47-5f2c-4550-8153-0f91c3a31d06](https://cloud.githubusercontent.com/assets/15378253/22637810/36c92e00-ec7f-11e6-9881-9960044438d1.png)
@bpoplauschi  I create a new demo found unable to reproduce this issue.May be the cause of my own project.

**Comment by boycechang** [comment] 2017-02-06 08:32
@bpoplauschi encountered the same issue in my project.

**Comment by LanYanQin** [comment] 2017-02-06 08:34
@boycechang You also like this?I have a problem now used in the project, if you are creating a new DEMO, there is no problem.

**Comment by boycechang** [comment] 2017-02-06 08:48
@LanYanQin exactly the same. 
<img width="1401" alt="screen shot 2017-02-06 at 16 45 44" src="https://cloud.githubusercontent.com/assets/1205800/22640049/ebad3634-ec8b-11e6-8762-a5a0b2deaeec.png">

**Comment by boycechang** [comment] 2017-02-06 10:59
@LanYanQin @bpoplauschi  This problem seems caused by Xcode project cache. Flow the steps bellow can fix this issue.
1. Clean Build.
2. Reset Simulator.
3. Restart Xcode.
4. Delete your DerivedData folder in ~/Library/Developer/Xcode/DerivedData.
5. Delete the contents (not the whole folder) of /var/folders.
6. Restart Computer.

**Comment by LanYanQin** [comment] 2017-02-07 02:40
@boycechang I solved the problem of your idea.

**Comment by bpoplauschi** [comment] 2017-02-07 06:01
Great to hear. Closing based on the previous comments.

**Closed by bpoplauschi** 2017-02-07 06:01 UTC
