### ISSUE TITLE
GIF is always nil when retrieved from memory

### ISSUE THREAD

**Issue by liakhandrii** [rs/SDWebImage#2216] opened 2018-02-09 09:56 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name            | iOS
 Platform Version         | 11.2
 SDWebImage Version      | 4.3.0
 Integration Method     | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 100%
 Demo | https://github.com/liakhandrii/sdwebimageissuedemo

### Issue Description and Steps

I try to load some GIFs in a UICollectionView and everything is fine on the first load, when the image is downloaded from the Internet or loaded from disk. When the cells are reused, the images are loaded from memory, but in that case they all become empty. 
When the image is loaded from memory, the `data: Data?` in callback is nil, so I have to work with `loadedImage: UIImage?`, which is not nil. I try getting the data of `loadedImage ` and constructing an `FLAnimatedImage` myself, but it doesn't work. I try calling `loadedImage?.sd_FLAnimatedImage`, it doesn't work too. 

By the way, if I try get the image from `loadedImage: UIImage?` when image is loaded from disk or web, it doesn't work too.

This code will work fine the first time it's run, but it won't the second time.
It'll work fine if I disable the memory cache, but I can't just disable it, I need it.
```swift
let url = URL(string: "https://i.giphy.com/media/JIX9t2j0ZTN9S/200w_d.gif")!
SDWebImageManager.shared().loadImage(with: url, options: [], progress: nil, completed: { (loadedImage, data, error, cacheType, success, _) in
    // This always contains some data
    let memoryImageData = loadedImage?.sd_imageData()
    // This is nil in all situations
    let gifFromUiimage = FLAnimatedImage(animatedGIFData: memoryImageData) ?? loadedImage?.sd_FLAnimatedImage
    // This is ok only when the image is loaded from disk or web
    let gifFromData = FLAnimatedImage(animatedGIFData: data)
                
    cell.animatedImageView.animatedImage = gifFromUiimage ?? gifFromData
})
```

**Comment by dreampiggy** [comment] 2018-02-09 11:04
I'll check this issue later. We introduce a performance improvements for FLAnimatedImageView to bind FLAnimatedImage to UIImage with associated object, so that we can store it into memory cache. This strategy may have some race condition.

It's better to provide a demo which can reproduce this issue to let us identify the problem. Thanks for report.

**Comment by liakhandrii** [comment] 2018-02-09 11:31
@dreampiggy created a demo and added it to the table above.

**Comment by dreampiggy** [comment] 2018-02-10 02:08
Maybe this change break the previous behavior. But we should make more consideration on this.

For histrocal reason, we always query the disk cache when the image is an animated image. Which means for `UIAnimatedImage` created by `-[UIImage animatedImageWithImages:duration:]`, we always query the disk cache even the image instance is in memory cache. This is not a designed behavior but we used to. This is just to solve the problem that `FLAnimatedImage` need the data.
However, for static `UIImage`, we always do not query disk cache and return the `data` args with nil.

So, if you really need the data, you should now pass a extra options `SDWebImageQueryDataWhenInMemory`. I will mark this into the usage in [wiki page](https://github.com/rs/SDWebImage/wiki/Common-Problems)

**Comment by dreampiggy** [comment] 2018-02-10 02:15
And one more thing. That `sd_imageData()` method is an API to encode the `UIImage` into `NSData`. So most cases you do not need this because this encoding need time and the produced data may not equal to the original data from the network 😅

**Comment by liakhandrii** [comment] 2018-02-12 13:05
I tried it, and `SDWebImageQueryDataWhenInMemory` works, but not always. For some images `data` is still `nil`. I can reproduce this only in iPhone 8 simulator, though. In iPhone 8 Plus simulator it works fine. I updated my demo project to demonstrate this issue.

**Comment by liakhandrii** [comment] 2018-02-13 10:42
Update: I checked on a real device, Adding `SDWebImageQueryDataWhenInMemory` makes no difference on it. The `data` is `nil`.

**Comment by dreampiggy** [comment] 2018-02-13 13:06
If you using `cacheMemoryOnly`, this will force the downloaded image data disappear. Only the `UIImage` instace keep in `SDImageCache`. So this is also a designed behavior.

For now and future implementation (If not change from the scratch). Memory cache only keep the `UIImage` instance but not `NSData`. So when you need the data, you should always prefer disk cache.

Through in 5.x, we introduce a `SDAnimatedImage` which you can obtain the data again through its property. You should not relay on this because it can be changed by other class which adopt `SDAnimatedImageProtocol`.

**Comment by dreampiggy** [comment] 2018-04-07 13:33
It seems that this issue is more about usage now. And the question is over. So I'll close this to keep the tracklog more clearly.

If you still have some questions about this, feel free to reopen it :)

**Comment by YasinZhou** [comment] 2018-04-28 04:05
In FLAnimatedImageView+WebCache , the default value for  `options` is 0，
there isn't have the sd_FLAnimatedImage assignment when other views load the image first, and then load cache ,it will don,t have the imageData,GIF will be nil

**Comment by dreampiggy** [comment] 2018-04-28 05:30
@YasinZhou Do you mean this case ?
`UIImageView` 1 request -> `www.foo.bar/1.gif` -> Download and cache to memory/disk cache, no asscoaited object in memory cache
`FLAnimatedImageView` 2 request -> `www.foo.bar/1.gif` -> Memory cache hit, return `image` without data

If so, please reply and I'll give some reason and consideration to this

**Comment by YasinZhou** [comment] 2018-04-28 06:49
yes

**Comment by dreampiggy** [comment] 2018-04-28 08:43
@YasinZhou I see..

To fix this issue, we maybe have two choice. But firstly I want to say something about previous version (I remember is 4.0.0-4.2.0) SD and FLAnimatedImage.

`FLAnimatedImage`'s biggest disadvantage is that it's not a subclass of `UIImage`, but a `NSObject`. This means we can not store it into image cache. Because our image cache's memory cache only store the `UIImage` instance, but not any `NSData` or `FLAnimatedImage`. Our image cache's disk cache only store `NSData`. I don't think we need to change this because this will cause many issues.

So what we do in previous version SD for FLAnimatedImage. It's using a tricky logic. It's the following one:

+ If memory cache hit, and the `UIImage.images` is not nil, everytime we query memory cache, we will call `- [NSData dataWithContentOfFIle:]` synchronically to query the disk :). So if you query multiple GIF images, your main queu may be blocked and frame rate may drop during scrolling
+ If memory cache miss, then query the disk cache in global queue and callback `NSData`.

Since most cases, you only display GIF images on `FLAnimatedImage` but not `UIImageView` if you decide to use that `GIF` subspec. To fix the performance for this, we change it to current implementation. Which means we will bind a `sd_FLAnimatedImage` into UIImage to image cache.

**Comment by dreampiggy** [comment] 2018-04-28 08:58
So now, let's talk about this case:

1. `UIImageView` request -> `www.foo.bar/1.gif` -> Download and cache to memory/disk cache

After this step, actually we do not know any information about the image in the cache to specify that it's a `GIF` image. Because if you use `UIImageView` to request, it's been treated as `Static GIF` image and will draw as a CGImage during `shouldDecompressImage`. Any information in image instance itself has been lost.

This can not be easily solved because since we don't know what image original source is an  `Animated GIF`...And creating animated images cause extra CPU/Memory usage. So you can not always store the full animated images in the memory. Because most cases' performance will be impacted.

I can give a solution (Not so great). If you know your images is animated GIF, and you're current request image using `UIImaegView`. Manually create `FLAnimatedImgage` instance and bind `sd_FLAnimatedImage` in the completion block to that image. Then the image in the cache should works for latter `FLAnimatedImageView` request.

**Comment by YasinZhou** [comment] 2018-04-28 09:45
Thank you very much for your answer!
i'm using three Kinds of imageView,FL/UI/ASDK, only FL need `sd_FLAnimatedImage`, and i've encapsulation FL, there's a unified call entry, so i can set all the FL reques's options is 'SDWebImageQueryDataWhenInMemory'.  though it's not so great too.

**Comment by dreampiggy** [comment] 2018-04-28 09:58
@YasinZhou Well...`SDWebImageQueryDataWhenInMemory` may cause `JPEG/PNG` images also query the disk data. (Though this one is asynchronized, not block main queue). But I think not all people need this. So now it does not become the default options. You can consider to write another convenience method such as `sda_setImageWithURL:` which provide this one as a default option....

In 5.x, we will move FL to another repo and use our own solution for animated image/imageView. See #2140 . Which may solve many issue about FL to integrate with SDWebImage's Core feature. It's welcomed to try that ;)

**Comment by YasinZhou** [comment] 2018-04-28 10:12
and there is a performance question, i found the image cache loading slowly, loading 21 disk caches in about 6 seconds

**Comment by YasinZhou** [comment] 2018-04-28 10:28
Your suggestion was right, I judged images's url `rangeOfString:@".gif"`

**Comment by dreampiggy** [comment] 2018-04-28 10:52
For disk cache performance, are you using WebP images ? If so, see #2245

**Comment by YasinZhou** [comment] 2018-04-28 10:57
yes, it's webp

**Closed** 2018-07-16 18:45 UTC
Labels: GIF
