### ISSUE TITLE
When I open and kill the app multiple times(over 30 times), multiple blue dots will appear in the picture.

### ISSUE THREAD

**Issue by xiaopeijun** [rs/SDWebImage#2368] opened 2018-06-29 08:52 UTC
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.3.1
 SDWebImage Version      | 4.4.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.3
 Repro rate              | all the time (100%)

### Issue Description and Steps

When I open and kill the app multiple times(over 30 times), multiple blue dots will appear in the picture.

The original full image:
![timg](https://user-images.githubusercontent.com/14288146/42083288-079bc268-7bbd-11e8-8ea3-6581044892cd.jpeg)

After open and kill the app multiple times:
<img width="839" alt="time1" src="https://user-images.githubusercontent.com/14288146/42083287-0765d4fa-7bbd-11e8-8500-48f9adf42a98.png">

**Comment by dreampiggy** [comment] 2018-07-01 04:14
Sounds really strange. We didn't face this issue from our products. Any good to reproduce this ? 😕

**Comment by GaevYuriy** [comment] 2018-07-24 19:04
Hi, maybe some additional info can help to solve this problem. Al first, as it was mentioned by @xiaopeijun, image artifacts appear only, when you kill app several times. As I understand, it downloads image multiple times and  SDWebImage saves it to the local cache, using image compression. However, these artifacts appear only at the moment, when image compression goes So, the first idea was to turn off image decompression by this methods 

SDWebImageManager.shared().imageDownloader?.shouldDecompressImages = false
SDWebImageManager.shared().imageCache?.config.shouldDecompressImages = false

However, it didn't help and they again appeared. So, I decided to delete the app and reinstall (as I thought, that I will clean local cache), in the result, all image artifacts have disappeared. However, it is not the full solution, as, in some period of time, they have appeared again.

**Comment by dreampiggy** [comment] 2018-07-25 03:18
@GaevYuriy SDWebImage store the **original image data** into your disk cache, not the decompressed one or re-encoded one.  (Until you specify [cacheSerializer](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.h#L215-L235))

Did you specify anything transformer for the image display ? Such as [this delegate](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.h#L156-L166) here in 4.x

**Comment by GaevYuriy** [comment] 2018-07-25 06:29
@dreampiggy No, neither cacheSerializer nor any transformer is specified for image display. I use this method to [download](https://github.com/rs/SDWebImage/blob/9d1d38b1988c4aecf22bce249a29c75d703df1e6/SDWebImage/SDWebImageManager.h#L275) it. Also, when I checked the cache type in the response handler, it was the memory. And, when I set [refreshCached](https://github.com/rs/SDWebImage/blob/9d1d38b1988c4aecf22bce249a29c75d703df1e6/SDWebImage/SDWebImageManager.h#L46) options the problem has disappeared, however it is not a solution, as SDWebImage redownloads the image and save to cache

**Comment by dreampiggy** [comment] 2018-07-25 07:13
@GaevYuriy You means, when this strange issue appear, your image instance is from memory cache (`SDImageCacheTypeMemory`) ? Interesting.

The memory cache now just use `NSCache`, it should not modify the image instance...

Could you please try to reproduce this issue, and then, set a debug breakpoint, triiger `[[SDImageCache sharedImageCache] clearMemory]` to remove the memory cache, and let it been retrieve from disk cache to see what happend ?

**Comment by GaevYuriy** [comment] 2018-07-25 08:24
@xiaopeijun,  I'm not sure if I did it correctly, so I will write my steps

1. Reproduced bug

2. Check, image from disk and from memory cache with cacheKey(for URL)

`
let diskCachedImage = self.imageCache?.imageFromDiskCache(forKey: self.cacheKey(for: url))
let memoryCachedImage = self.imageCache?.imageFromMemoryCache(forKey: self.cacheKey(for: url))
`
Both of them were with artifacts.

3. When I called, SDImageCache.shared().clearMemory(), I received disk cache type in response handler and image was still with artifacts

**Comment by dreampiggy** [comment] 2018-07-25 08:52
@GaevYuriy From your stops. It seems that the disk cache image data is already been modified. Because I can ensure that the image decoding process will not change the representation of image.

So this time, let's try to figure out the reason. I can give you some steps to check. These step can be done on iPhone simulator to simplify the process.

+ Firstlly,reinstall your apps, remember one URL that can trigger this issue, download the image original data to desktop, named `original.jpg`.

+ Then, check your apps's sandbox and grab the same image to the desktop. You can do this from lldb by using `po NSHomeDirectory()` (See [here](https://stackoverflow.com/questions/35963940/document-folder-ios-simulator)). Then find the cache files in `./Documents/Library/Caches/default/com.hackemist.SDWebImageCache.default` from documents folder... Copy the image match the URL into desktop, named `cache.jpg`.

+ Next, trigger this issue until you see the blut dots. Then, check your app's sandbox again, grab the corrupted image files to desktop, named `bug.jpg`

Check whether these 3 images are equal. The desired result should be `original.jpg == cache.jpg, original.jpg != bug.jpg`. If so, we can ensure that the cache files in SDWebImage been modified accidentally.

**Comment by GaevYuriy** [comment] 2018-07-25 11:08
Maybe I found, what is the problem. So, I did step 1 and step 2, but at step 2 I have already found artifacts, they are small and hardly visible. 
Also, in my code, I have a method `DispatchQueue.global().async { self.saveImage(toCache: image, for: url) }`, when I load the image, I resave it to cache by hand. So, I resave an image from memory to memory, which scales artifacts, so it is the problem. So, now I can say, that this bug appears when SDWebImage saves images to the memory cache.

Original

![8fb6032fe3f22e184b1fea9e12786828](https://user-images.githubusercontent.com/23167917/43197531-22091e8c-9014-11e8-8383-e0fa352c5fe3.jpg)

Comparison with artifacts

<img width="1679" alt="2018-07-25 14 01 24" src="https://user-images.githubusercontent.com/23167917/43197567-37f4e636-9014-11e8-986d-2ee2a9ad8efe.png">

<img width="1679" alt="2018-07-25 14 01 34" src="https://user-images.githubusercontent.com/23167917/43197569-39a874e8-9014-11e8-8920-dbf265e94392.png">

**Comment by dreampiggy** [comment] 2018-07-25 13:40
@GaevYuriy You means each time you fetched the image (from cache or network), you call `SDImageCache.storeImage` ? This will cause issue because that method will try to encode thr `UIImage` memory representation, to thr compressed format image data(By dafault, JPEG for non-alpha image and PNG for alpha image)

Image encoding, which some iOS developer may not be familiar with, have lossy compression or lossless compression. However, JPEG fomat supports only lossy compression. Which means you encode - decode again, the image quantity was effected become worse. If you repeat several time, the final image may not be readable at all.

Through PNG supports lossless compression, however doing this may consume much more unuseful process. It's strongly not to do anything like this. (I guess this is a bug in your business code...Why to store and overwrite a disk image which already exist :consufed)

**Comment by bpoplauschi** [comment] 2018-09-07 12:45
Per latest comments, closing.

**Closed by bpoplauschi** 2018-09-07 12:45 UTC
Labels: awaiting response, not enough info
