### ISSUE TITLE
ColorSyncProfileCreateSanitizedCopy

### ISSUE THREAD

**Issue by seanLee** [rs/SDWebImage#1058] opened 2015-03-09 03:58 UTC
When I get a image from server,it prints ````*** ImageIO - could not find ColorSync function 'ColorSyncProfileCreateSanitizedCopy'````in console.

That's my code ````[imageView sd_setImageWithURL:url placeholderImage:[UIImage imageNamed:@"placer"]];````

**Comment by mythodeia** [comment] 2015-03-09 06:44
can you reproduce it with the demo project using your own image urls?

**Comment by rakii** [comment] 2015-03-10 12:15
I am facing the same issue when trying to load a gif from bundle to imageView

**Comment by mythodeia** [comment] 2015-03-10 12:41
does this happen to all gif images or to specific ones?

**Comment by seanLee** [comment] 2015-03-14 07:42
@mythodeia  no,I am not loading gif when this issue happened.this is my code ````UICollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:reuseIdentifier forIndexPath:indexPath];
    
    //clear Subviews
    [cell.subviews enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
       
        [obj removeFromSuperview];
    }];
    [cell setBackgroundColor:[UIColor whiteColor]];
    
    NSDictionary *dic = [self.resourceArray objectAtIndex:indexPath.row];
    
    if (self.resourceType == 0) {
        
        UIImageView *imageView = [[UIImageView alloc] initWithFrame:cell.bounds];
        NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"%@%@",kNetPath_Code_Base,[dic valueForKey:@"cover"]]];
        [imageView sd_setImageWithURL:url placeholderImage:[UIImage imageNamed:@"gukexiangqing_icon_list_photo"]];
        [cell addSubview:imageView];
    
    } else {
    
        BorderView *borderView = [[BorderView alloc] initWithFrame:cell.bounds];
        [borderView setBackgroundColor:[UIColor whiteColor]];
        borderView.borderInsets = UIEdgeInsetsMake(0, Margin_Left, 1.f, 0);
        
        UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(Margin_Left, 0, borderView.frame.size.width- 50.f, borderView.frame.size.height)];
        label.text = [dic valueForKey:@"name"];
        label.font = [UIFont systemFontOfSize:13.f];
        [borderView addSubview:label];
        
        UIImage *image = [UIImage imageNamed:@"wodeguke_icon_info"];
        UIImageView *imageView = [[UIImageView alloc] initWithFrame:CGRectMake(label.frame.size.width + (50.f - image.size.width) / 2, (label.frame.size.height - image.size.height) / 2, image.size.width, image.size.height)];
        imageView.image = image;
        [borderView addSubview:imageView];

        [cell addSubview:borderView];
    }
    
    return cell;````
it's really a general use for load a image from server

**Comment by mythodeia** [comment] 2015-03-14 07:47
do you have sample images that produce this console warning?

**Comment by seanLee** [comment] 2015-03-17 08:39
@mythodeia sorry,it's too busy for recent time.For now,I have nothing changed,but it does't print anything in console.

**Comment by mythodeia** [comment] 2015-03-19 12:50
as far as i understand this is an issue with some images and it has to do with the way they were created/edited etc. 
since this is not a crash, rather than a warning i will close this for now. if you have more info please reopen
thanks

**Closed by mythodeia** 2015-03-19 12:50 UTC

**Comment by seanLee** [comment] 2015-03-22 08:28
@mythodeia  OK!Thanks for the awesome lib.
