### ISSUE TITLE
the image is rotated ..

### ISSUE THREAD

**Issue by samiibnauf** [rs/SDWebImage#75] opened 2012-03-03 11:54 UTC
I used SDWebImages like this :
    [avatar setImageWithURL:[NSURL URLWithString:@"http://url.of.image"]
               placeholderImage:[UIImage imageNamed:@"placeholder.png"]]; 

it works fine .. but when the height of remote image is bigger than width ( ex :  100 \* 250)  the image is rotated by force .. how to prevent image rotation and show image as it is .. 

thanks..

**Comment by peterjkirby** [comment] 2015-01-05 13:28
I am using SDWebImage 3.7.1 and am also seeing this issue.

**Comment by samkass** [comment] 2015-01-14 05:13
I see images rotated if the EXIF data specifies a different rotation than the image data is stored.  (ie. an image stored in landscape that you know should be displayed portrait only because of its EXIF.)

**Comment by mythodeia** [comment] 2017-03-13 09:56
can anyone confirm this issue still exists in the latest version? 
UIImageJPEGRepresentation strips the image of its metadata so if the image has orientation information inside the EXIF metadata this will be lost.

**Comment by mythodeia** [comment] 2017-03-28 13:09
i will close this as its been quite some time since this one was mentioned

**Closed by mythodeia** 2017-03-28 13:09 UTC
Labels: bug

**Comment by samkass** [comment] 2017-03-28 13:18
It doesn't look like my pull request was ever integrated. It's easy enough to reproduce. I had to fork it over this issue so don't know if the root still has the issue.

**Comment by uvios** [comment] 2020-09-25 16:07
i am faxing this issues is there a fix ?

**Comment by levino** [comment] 2022-09-15 13:12
> i am faxing this issues is there a fix ?

Which number did you fax it to?

**Comment by uvios** [comment] 2022-09-15 13:52
> > i am faxing this issues is there a fix ?
> 
> 
> 
> Which number did you fax it to?

This proves even the old mitsakes can be corrected when pointed out

**Comment by levino** [comment] 2022-09-15 14:07
> > > i am faxing this issues is there a fix ?
> > 
> > 
> > Which number did you fax it to?
> 
> This proves even the old mitsakes can be corrected when pointed out

Glad you took my little joke as it was meant. Have a nice day!
