### ISSUE TITLE
Why does tableViewCell`s imageView don`t flash when sdwebimage put image

### ISSUE THREAD

**Issue by zqpmaster** [rs/SDWebImage#1499] opened 2016-03-17 02:32 UTC
**I found that imageview don`t flash on this code in a tableViewCell`s imageView.

```    
[self sd_setImageWithURL:[NSURL URLWithString:imageSourceUrl] placeholderImage:[self getPlaceHolderImage] options:SDWebImageAvoidAutoSetImage completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            self.image = image;
    }];
```

**But it flash on it .

```    
[self sd_setImageWithURL:[NSURL URLWithString:imageSourceUrl] placeholderImage:[self getPlaceHolderImage] options:SDWebImageAvoidAutoSetImage completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            // do someting with image
           dispatch_sync(dispatch_get_main_queue(), ^{
               self.image = image;
           });
        });
    }];
```

**They all are tableViewCell`s imageView, they wil be reused.

I wish they don`t flash, but I want to know the reason why they flash.

**Comment by vivekshah05** [comment] 2016-04-29 09:27
Hello @zqpmaster  i am facing the same issue, if you found the solution can you pls help me ?

**Comment by zqpmaster** [comment] 2016-04-29 14:06
@vivekshah05 I deeply look the sdImage soure code and I found that the second piece code asyn two twice in main queue.But the first piece code not. Maybe it is the reason why the image flash in second piece code. Hope to help you.

**Comment by bpoplauschi** [comment] 2016-05-29 18:47
This is a duplicate of #1543

**Closed by bpoplauschi** 2016-05-29 18:47 UTC
