### ISSUE TITLE
OOM - Terminated due to memory error 

### ISSUE THREAD

**Issue by guidev** [rs/SDWebImage#1953] opened 2017-06-30 22:52 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.1.x and lower (tested also on 10.0.x, 9.3.x) 
 SDWebImage Version      | 4.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3.3
 Repro rate              | all the time (100%)
 Repro with our demo prj | no
 Demo project link       | https://github.com/gorillatech/SDWebImage-OOM-sample

### Issue Description and Steps

When using SDWebImagePrefetcher to preload thousands of non-existent images (404 error), the app starts to use a lot of memory.

Eventually the app gets terminated by the OS.

I've attached a demo project that highlights the problem.

It only happens on 10.1.x and lower.

<img width="912" alt="screen shot 2017-07-01 at 00 38 35" src="https://user-images.githubusercontent.com/1105813/27756379-368b2238-5df7-11e7-9856-ccc5f07972ce.png">

**Comment by bpoplauschi** [comment] 2017-07-24 18:02
Interesting issue. Did you debug in detail to see what the cause of the increasing memory is @guidev?

**Comment by dreampiggy** [comment] 2017-08-02 15:41
Yeah, interesting issue. I try that demo project(I just use 20 urls and add an simple log completion block to check because it may show clearly) and use Instruments to check. On iOS 10.3, it does not cause memory leak. All the 20 `NSURLSessionTask` instances dealloc by order during the completion.

<img width="1280" alt="2017-08-02 11 31 08" src="https://user-images.githubusercontent.com/6919743/28881506-e6ca2caa-77da-11e7-99a2-8b20fcf1381c.png">

But on that iOS 9.0 simulator, 20 `NSURLSessionTask` instances do not dealloc after all the completion block called and cause all the NSURLSesionTask releated instance (Whatever that retained CFNetwork instance and Foundation instance). Yes, it leaked.

<img width="1280" alt="2017-08-02 11 27 07" src="https://user-images.githubusercontent.com/6919743/28881697-8e6430b4-77db-11e7-9008-b998235564bc.png">

But I can't simply find the reason why this cause memory leak(there are no retain cycle in `SDWebImagePrefetcher`), and SD does not use any OS version specify API of NSURLSession. It may related to the NSURLSession internal changes. If someone can help with this and find the reason, please provide the information, thanks 😕

**Comment by bpoplauschi** [comment] 2017-08-02 15:56
I think the key here is trying to load thousands of url's that will cause 404. This is a bit off, even if we should not crash.

**Comment by dreampiggy** [comment] 2017-08-02 16:07
Well, regardless of the usage. There is actually memory leak issue even if I load just 20 urls which responsed 404 on the 10.1.x and lower(?). For most situation,this will not cause problems because each url the leak is just less than 100KB. But if someone can find the reason and solve this, it will make the library become more strong and stable. 😀

**Comment by bpoplauschi** [comment] 2017-08-03 09:44
@dreampiggy I agree. I did not add it to the 4.1.1 milestone as I don't see this as an urgent issue.

**Comment by dreampiggy** [comment] 2017-08-04 08:09
@bpoplauschi Agreed. If only someone can find out the reason and better provide an fix. 😀

**Comment by dreampiggy** [comment] 2018-01-28 16:10
Found the reason. If your URLSession delegate response to the `URLSession:dataTask:willCacheResponse:completionHandler:`, but you do not call the `completionHandler`. Then the memory leak below iOS 10.

We totally remove this override delegate method in #2197. So that demo does not cause memory leak again. And this change also fix the current wrong cache bahavior when you use `SDWebImageDownloaderUseNSURLCache` or `SDWebImageRefreshCached`

**Comment by dreampiggy** [comment] 2018-01-30 02:52
Fixed by #2197. In 4.3.0 release.

**Closed by dreampiggy** 2018-01-30 02:52 UTC
Labels: bug
