### ISSUE TITLE
About URL contains Chinese

### ISSUE THREAD

**Issue by hrscy** [rs/SDWebImage#1919] opened 2017-06-01 02:41 UTC
### About URL contains Chinese
My URL has Chinese, so this image will not show,I found the reason.
The URL can not be used directly,use the following methods:
```
[imageView sd_setImageWithURL:[NSURL URLWithString:[myURL stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]] placeholderImage:[UIImage imageNamed:@"placeholder_picture"]];
```
But I have so many URLs,so I need this setting like that every time.
So I'd like to make a suggestion about my issue whether 'NSUTF8StringEncoding' can be integrated into the framework?

**Comment by skyline75489** [comment] 2017-06-13 10:57
The problem is not `NSUTF8StringEncoding`. The problem is about "escaping". URLs must be escaped.

**Comment by mythodeia** [comment] 2017-06-13 12:47
closing this. the urls must be escaped as @skyline75489 suggested.

**Closed by mythodeia** 2017-06-13 12:47 UTC
