### ISSUE TITLE
 CFRunLoopRun(); crash

### ISSUE THREAD

**Issue by lengqingfeng** [rs/SDWebImage#1262] opened 2015-08-18 03:59 UTC
CFRunLoopRun();
in ios6.1.3 crash

**Comment by mythodeia** [comment] 2015-08-18 05:42
can you please be more specific? this does not help at all. are you using the latest version of this library? can you provide the crash log? can you replicate it in the demo project?

**Comment by vidcina** [comment] 2015-08-18 05:48
I have the same problem. It appears randomly and really hard to reproduce.

**Comment by armnotstrong** [comment] 2015-08-22 08:49
Hi, we came to the same issue, when scroll the UITableView very fast. randomly the scrolling may be frozen and  here is how we invoke `SDWebImage`:

     - (void)configureImageWitURL:(NSURL *)imageURL
{
    @weakify(self);
    [self sd_setImageWithURL:imageURL placeholderImage:nil options:SDWebImageRetryFailed progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        @strongify(self);
        [self.progressView setProgress:receivedSize / (float)expectedSize];
    } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        @strongify(self);
        self.progressView.hidden = YES;
        if (cacheType != SDImageCacheTypeMemory) {
            self.alpha = 0;
            [UIView animateWithDuration:0.3 animations:^{
                self.alpha = 1;
            }];
        }
    }];
} 

And here is the screenshot of Xcode when the list got frozen and crashs:

![error](https://cloud.githubusercontent.com/assets/3839691/9423209/79e9e74c-48ed-11e5-89d8-dee0a293a54e.png)


Hope this may help figuring out where the problem is.

**Comment by timkoma** [comment] 2015-08-22 11:31
I think that there is a bug in SDWebImage: progress block gets called on background thread.

try to call the body of the progress block method using dispatch_async:

dispatch_async (dispatch_get_main_queue(), ^{
        @strongify(self);
        [self.progressView setProgress:receivedSize / (float)expectedSize];
});

**Comment by armnotstrong** [comment] 2015-08-24 06:13
@timkoma I tried `dispatch_async`, and it seems problem solved, (Though I'm not very certain of that, because this happened randomly, but I haven't came to that problem since change the code with `dispatch_async`). Thanks

**Comment by timkoma** [comment] 2015-08-24 07:30
https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png

**Comment by bpoplauschi** [comment] 2016-10-06 13:44
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).

**Closed by bpoplauschi** 2016-10-06 13:44 UTC
Labels: bug
