### ISSUE TITLE
-[SDWebImageDownloaderOperation start] Crash in latest version

### ISSUE THREAD

**Issue by Monika-Tapadiya** [rs/SDWebImage#1342] opened 2015-10-16 12:37 UTC
Hello, 
I have used SDWebImageCache to load images but it is crashing sometimes, I got line no. 

-[SDWebImageDownloaderOperation start]  (SDWebImageDownloaderOperation.m:96)
 self.connection = [[NSURLConnection alloc] initWithRequest:self.request delegate:self startImmediately:NO];

Please help me  to solve the issue.

Thanks

**Comment by bpoplauschi** [comment] 2015-10-16 12:53
Probably a duplicate of https://github.com/rs/SDWebImage/issues/691

**Comment by bkvirendra** [comment] 2015-10-16 17:00
@bpoplauschi I faced the issue! Is there something particularly to do with the way we use SDWebImage?

**Comment by skytraveler** [comment] 2016-03-04 12:13
It contributes 1/2 of all crashes we've got. Could someone kindly fix it? Thx.

**Comment by sunbohong** [comment] 2016-03-04 14:01
@skytraveler  is there a solid way to reproduce this crash?

**Comment by bpoplauschi** [comment] 2016-10-06 13:45
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).

**Closed by bpoplauschi** 2016-10-06 13:45 UTC
Labels: crash
