### ISSUE TITLE
 Is there a BUG that sd_setImageWithURL completed with a wrong image? 

### ISSUE THREAD

**Issue by willbin** [rs/SDWebImage#1123] opened 2015-04-14 07:09 UTC
```
[aActionIV sd_setImageWithURL:tryURL
             placeholderImage:holderImg
                      options:SDWebImageRetryFailed | SDWebImageLowPriority
                     progress:^(NSInteger receivedSize, NSInteger expectedSize)
     {
         if (expectedSize > 0)
         {
             float progress = receivedSize / (float)expectedSize;
             [loadingIndicator setProgress:MAX(MIN(1, progress), 0) animated:YES];
         }
     }
                        completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)
     {
         [loadingIndicator removeFromSuperview];

         if (error)
         {
             NSLog(@"%@", error);
         }
         else
         {
         }
     }];
```

I have some UIImageView that using `sd_setImageWithURL` to load images.
But after `pod update` SDWebImage to `3.7.2`, sometimes one UIImageView will show wrong image that belongs to other URL. 
Just like two UIImageView exchange their images.  And when I change SDWebImage to `3.7.1`, everything is OK.
So weird!
Now the question, 
Is there a BUG that sd_setImageWithURL completed with a wrong image?

**Comment by devlvpw** [comment] 2015-04-27 08:00
I have the same problem.

**Comment by timkoma** [comment] 2015-04-27 08:10
One note: progress:^(NSInteger receivedSize, NSInteger expectedSize){} - can be called from background thread - use dispatch_(a)sync(dispatch_get_main_queue(), ^{}) there if you need update UI

**Comment by lvpengwei** [comment] 2015-04-27 08:26
@timkoma This problem not happen in 3.7.1.

**Comment by lvpengwei** [comment] 2015-04-27 08:36
@willbin How you reproduced?

**Comment by willbin** [comment] 2015-04-28 03:24
@lvpengwei Changing to version 3.7.1 will fix this bug.
But @rs should do something to fix it in 3.7.2

**Comment by jjepsen** [comment] 2015-06-17 14:43
I also have this problem. Version 3.7.2 sometimes (error rate around 1/20 for me) sets the wrong image. The issue is not reproducible with version 3.7.1.

**Comment by jiekewei** [comment] 2015-07-07 07:55
I,m using Version 3.7.1 also have this problem

**Comment by mythodeia** [comment] 2015-07-07 09:42
@jiekewei @willbin @jjepsen @lvpengwei  have mentioned that with 3.7.1 there is no issue. 
Are you sure you are having the same issue with v3.7.1?

**Comment by jzaccone** [comment] 2015-10-04 13:48
I have the same problem with 3.7.1. The URL that comes back in sd_setImageWithURL is correct, but the wrong image is cached to that URL. 

The handler is called with cacheType = SDImageCacheTypeMemory.

    [imageView sd_setImageWithURL:[NSURL URLWithString:url] placeholderImage:placeholderImage completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
    // URL is as expected, but Image is wrong
    }];


This problem isn't consistent, but of course once it happens, it loads the wrong Image every time until the cache is cleared

**Comment by VersionMismatch** [comment] 2015-11-30 20:47
Did anyone found and confirmed a version were this issue is not happening?

**Comment by onurvarrrr** [comment] 2016-02-08 08:38
maybe related with iOS 9 ?

**Comment by timkoma** [comment] 2016-02-09 17:38
I wondering if it may be related to cell reusing in TableView/CollectionView. 
Old image load operation completed right after the new one. 
I'm aware of the [self sd_cancelCurrentImageLoad]; but maybe it is too late to cancel, and new image is cached on disk-  operation is done very quickly and finished download replaces the the cached one. 

Canceling is not done very correctly - I think there is a need to wait for canceled callback and then continue with processing new downloaded image

**Comment by rrallo** [comment] 2016-02-20 00:06
I'm seeing this on 3.7.4 and the only way I've been able to get around this is to clear the cache much more often. :(

An idea my colleague suggested is to check the MD5 hashes, but this would require sending these with the payload, which will be a pretty big workaround and not very optimal.

I'm seeing exactly what @jzaccone is describing.

My theory is that maybe there's a race condition when writing the images to the cache, as I don't see threading controls in those methods.

Any insight is much appreciated.

**Comment by ppaulojr** [comment] 2016-02-24 15:23
I'm seeing this bug with 3.7.5 

```
	[self.badgeView sd_setImageWithURL:[NSURL URLWithString:badge.image_path]];
```

Sometimes get an empty image

**Comment by mythodeia** [comment] 2016-02-24 20:56
@ppaulojr the empty image you are seeing is caused by something else which is discussed #1457

**Comment by bpoplauschi** [comment] 2016-03-27 15:29
Closing based on the last comment

**Comment by bpoplauschi** [comment] 2016-03-27 15:30
Oh, sorry. The original issue by @willbin is a different one from the one @ppaulojr reported and is fixed by #1496. Reopening

**Comment by drakon** [comment] 2016-04-15 11:03
I think I have the same problem. Using version 3.7.5.

Was testing lazy loading images in a table view. I figured that if an image loaded, I scroll to another position in the table and back to the start, the first image is replaced with an image from further down the list. It's pretty easy to reproduce on my side when I slow down the internet connection.

I assume it has something to do with reusing cells and not correctly cancelling downloads. After I added this to the cell it didn't happen again:

    override func prepareForReuse() {
        super.prepareForReuse()
        self.imageView.sd_cancelCurrentImageLoad()
    }

**Comment by mythodeia** [comment] 2016-04-15 11:06
In your prepareforreuse method change the image to nil
without cancelling the operation

**Comment by drakon** [comment] 2016-04-15 11:14
Why do you mean?

**Comment by mythodeia** [comment] 2016-04-15 11:16
in objc
```
-(void)prepareForReuse{
   your_image_view.image = nil
}
```

**Comment by drakon** [comment] 2016-04-15 11:22
Yeah, I got that. :)

But why do you think it makes a difference to just cancelling? Seems to work like that for me (the image itself is later changed if needed). 

The important point to me seems that the download needs to be cancelled, otherwise it will overwrite the image from the current cell (setting to nil may have the same effect though). Which is what this bug is about since it shouldn't be necessary when I understand SDWebimage correctly.

**Comment by bpoplauschi** [comment] 2016-05-08 16:20
There are a number of potential causes for this issue:
- 1st one that crosses my mind is #897 where we switched from 2 max concurrent downloads to 6 which may have surfaced an older issue
- another potential cause is #996 that changed a bit the way we load and decompress images.

But the bottom line is: if the solution @mythodeia proposed (`prepareToReuse` set the image to nil) works, you should use that.
I think this was a must even for older versions of SDWebImage. The reason is if you are using table views or collection views which reuse cells, due to scrolling the same imageView will start requests for different images and we must make sure only the last request is actually finalised and the imageView is always reset before being reused.

Thoughts?

**Comment by drakon** [comment] 2016-05-10 10:33
Well, my solution also worked. :) - I don't think it should be necessary though. I'd expected SDWebImage to cancel the previous download if I start a new one on the same UIImageView (or is there a case where you wouldn't want to have this behavior?). The solution with manually resetting works good in general I think. Would need to mention it in the docs (even if it's only until it is fixed).

I think this is what happend in my case:
- Start table view
- First cell is loaded
- First image is requested 
- First image is downloaded, inserted and cached (<- this is important I think for it to be reproducible)
- Scroll down
- Same cell is reused
- New image is requested
- Scroll up to first cell
- First image is requested from cache and inserted immediately
- Second image is downloaded and replaces the first image that was loaded from cache 
- Now we have the second image in the first cell

But again, I don't think it's super urgent to fix this since the workaround works pretty good even without accessing the source.

**Comment by arnaudlamy** [comment] 2016-09-05 09:49
Hi All,

I'm in 3.8 and I still have the same issue, I tried to add the @drakon method to my cellView but it just cancelled the image load. I'm a beginner with ios9, so I'm pretty I don't understand the workaround here. Any help will be welcome ! :smiley: 

Here's my code:

```
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("MessageCell", forIndexPath: indexPath)
        if let imageView = cell.viewWithTag(104) as? UIImageView {
            if imageView.image == nil{
                print("Update Image:  ", indexPath.row)
                if  messages[indexPath.row].user!.avatarURL != nil {
                    print("AVATAR  ", indexPath.row)
                    imageView.sd_setImageWithURL(messages[indexPath.row].user!.avatarURL)
                }
                else{
                    // TODO: put no avatar image
                    print("NO AVATAR  ", indexPath.row)
                    imageView.image = UIImage(named: "no avatar")
                }
            }
            print("-----------------")
        }
        return cell
    }
```

**Comment by mythodeia** [comment] 2017-03-07 09:41
can anyone reproduce this on the latest version?

**Comment by jelenadj** [comment] 2017-03-08 13:30
@mythodeia same happens to me too.

**Comment by mythodeia** [comment] 2017-03-23 08:57
@jelenadj do you have a sample project we can look at?

**Comment by MrNiceMrGood** [comment] 2017-03-23 13:53
Try this:

`    func setImageAnimated(imageUrl:URL, placeholderImage:UIImage) {
        self.sd_setImage(with: imageUrl, placeholderImage: placeholderImage , options:SDWebImageOptions.avoidAutoSetImage, completed: { (image, error, cacheType, url) in
            if cacheType == SDImageCacheType.none {
                UIView.transition(with: self.superview!, duration: 0.2, options:  [.transitionCrossDissolve ,.allowUserInteraction, .curveEaseIn], animations: {
                    self.image = image
                }, completion: { (completed) in
                })
            } else {
                self.image = image
            }
        })
    }
`

**Comment by dreampiggy** [comment] 2018-01-15 12:54
@MrNiceMrGood This is not a bug for SDWebImage. This issue is related to animation, `UIView.transition` is a animator and will trigger the animation applied to the view itself. But however, you capture one image in the block (called `image1`) when it current showing on `cell1`. When you scroll down, `cell1` is resued and should be reset for showing `image2`, but the animtor will still use `image1` to render it.

And the cases that a disk query and download query at the same time, this can not happend because we call `sd_cancelImageLoadOperationWithKey` before any request. So there should not have such a situation to let the download image replace your disk cache image.

**Closed** 2018-01-15 12:57 UTC
Labels: bug

**Comment by Omeesh** [comment] 2018-01-25 10:53
use .refreshCached in sdWebImage option to resolve this issue

`  
            cell.imageOut.sd_setImage(with: URL(urlPath), placeholderImage: #imageLiteral(resourceName: "imgPlaceholder"), options: [.refreshCached], completed: { (image, error, cache, url) in
                if error == nil{
                    cell.imageOut.image = image
                    }
                }
            })`
