### ISSUE TITLE
The methods dealloc/cancelInternal/reset of SDWebImageDownloaderOperation make crashes

### ISSUE THREAD

**Issue by 1oo1** [rs/SDWebImage#1821] opened 2017-02-27 07:36 UTC
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | iOS
 Platform Version       | 8.0/9.3/10.2
 SDWebImage Version      | 4.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2.1
 Repro rate              | sometimes 5%
 Repro with our demo prj | not happen
 Demo project link       | none

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

<img width="630" alt="dealloc" src="https://cloud.githubusercontent.com/assets/6869135/23352304/5e3e9ca8-fd01-11e6-90a2-0c82ce8c1528.png">

<img width="767" alt="reset" src="https://cloud.githubusercontent.com/assets/6869135/23352500/6b112418-fd02-11e6-9571-88f17f4a4744.png">
<img width="826" alt="cancelinternal" src="https://cloud.githubusercontent.com/assets/6869135/23352502/70855702-fd02-11e6-8b38-81c5f27f8406.png">

**Comment by Nishant-goibibo** [comment] 2017-03-01 11:39
We are facing same issue.

**Comment by testmesut** [comment] 2017-03-03 07:45
We are facing same issue (when we have 200+ cells in our tableview). We can reproduce it everytime. (going to downgrade sdwebimage)

**Comment by gshe** [comment] 2017-03-03 10:20
We are facing same issue.

**Comment by skyline75489** [comment] 2017-03-04 09:02
Can you guys provide reproducible examples about the crash?

**Comment by 1oo1** [comment] 2017-03-04 10:27
In fact I didn't reproduce these crashes, just found them on CrashReports. 
@testmesut , If you can reproduce it, please provide examples to help.

**Comment by testmesut** [comment] 2017-03-06 07:10
Hi @1oo1 ,
I can reprudce with these steps.
- Load a tableview with over 200+ cells first time (images should be un-cached) 
- Scroll to bottom fastly

**Comment by aldolazuardi** [comment] 2017-03-10 10:04
@testmesut have you try downgrade sdwebimage? I'm still use version 3.7 and reproduce same crash. Crash did not happen in iphone 6s and up. I tried to put this below line in didMemoryWarning, it helps for several scroll but still got crash after several fast scroll

> SDImageCache.shared().clearMemory()

**Comment by IvanChan** [comment] 2017-03-13 07:33
I met the same problem and more

**Comment by PhilippeBoisney** [comment] 2017-03-13 15:00
Facing same issue with a tableview fills with +200 rows.
Happening every time user performs fast scrolling with a slow device (iPod Touch for example).

**Comment by PhilippeBoisney** [comment] 2017-03-14 13:34
@testmesut @IvanChan @1oo1 Hey guys ! I've performed a lot of test and find out that problem also occurred with other libraries like Nuke or Kingfisher. Actually, I don't know why but didReceiveMemoryWarning method was never called when app run out of memory.

Finally, after 10 hours of multiple tests, I've checked if crash with "fast scrolling" happened with other apps (Facebook, Instagram, etc...). And those apps crashed too, especially when image was loaded from cache (but not during first loading from url)

So I realized that was my device that caused the problem. Actually, my iPod touch wasn't reboot since a while, so I simply rebooted it.. and problem disappears. 

I mean It's fucking weird isn't ? I feel like I'm really stupid now...

**Comment by IvanChan** [comment] 2017-03-15 01:58
@PhilippeBoisney My problem might NOT be a memory issue, I set the memory cache size only to 5M.

And I think is multi-thread problem for downloader, since 4.0-beta work well for me.

**Comment by OmarPedraza** [comment] 2017-03-23 16:53
@IvanChan, 4.0 works for you?

It still crashes sometimes in my app...

**Comment by IvanChan** [comment] 2017-03-24 01:40
@OmarPedraza **4.0-beta** didn't seem to crash that much.

**Comment by CodeStage** [comment] 2017-04-06 13:03
We have this issue too, but not in huge numbers (0,007% of active users every day). Still it's number one in our crash list. I assume it happens in combination with collection views.

<img width="900" alt="crash" src="https://cloud.githubusercontent.com/assets/1439835/24755358/340d8696-1ada-11e7-8fd4-4a44fa2faf4b.png">

**Comment by roeeAsaf** [comment] 2017-04-23 10:52
I back to 3.8 )-:
when are you think that be a fix for this?

**Comment by OmarPedraza** [comment] 2017-04-27 09:53
@roeeAsaf, does version 3.8 not crash?

If not, it looks like a workaround (for the time being) for me.

**Comment by archpan** [comment] 2017-04-28 02:55
We are facing same issue.

**Comment by bpoplauschi** [comment] 2017-07-28 17:58
Should be fixed by #1940 - closing for now

**Closed by bpoplauschi** 2017-07-28 17:58 UTC
Labels: crash
