### ISSUE TITLE
crash happens on 8.x system devices

### ISSUE THREAD

**Issue by mzgreat521** [rs/SDWebImage#2230] opened 2018-02-27 12:41 UTC
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.x
 SDWebImage Version      | 4.3.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | I haven't tested

### Issue Description and Steps

When I use the version 4.2.3, everything goes well. After I update the version to 4.3.1, I run my preject on the 8.x system devices(including simulators and phones). The crash below happens:

Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)

Here is the log on the console:
dyld: Symbol not found: _NSURLSessionTaskPriorityHigh
  Referenced from: /Users/xx/Library/Developer/CoreSimulator/Devices/E25EAABB-E9D5-4854-9C8A-AC24786F66EF/data/Containers/Bundle/Application/2D5D82DF-3CED-4BD0-A600-B03B219DB07D/xxx.app/Frameworks/SDWebImage.framework/SDWebImage
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 in /Users/xx/Library/Developer/CoreSimulator/Devices/E25EAABB-E9D5-4854-9C8A-AC24786F66EF/data/Containers/Bundle/Application/2D5D82DF-3CED-4BD0-A600-B03B219DB07D/xxx.app/Frameworks/SDWebImage.framework/SDWebImage

Please tell me why it happens and how to solve it. Thank you!

**Comment by mythodeia** [comment] 2018-02-27 14:12
can you try the demo project on the same simulators and devices and report back? does it happen with all images or specific ones/

**Comment by dreampiggy** [comment] 2018-02-27 14:54
@mzgreat521 It seems that `_NSURLSessionTaskPriorityHigh` symbol not defined in iOS 8 system. Though the Apple's Doc says this defined. I think we should remove that priority code and provide a quick fix version. :(

**Comment by dreampiggy** [comment] 2018-02-27 15:12
See this #.

**Comment by mzgreat521** [comment] 2018-02-28 03:05
@mythodeia @dreampiggy Get it. Thank you very much!

**Comment by dreampiggy** [comment] 2018-02-28 03:27
@mzgreat521 You can quick fix by import `CFNetwork.framework` in your main Application. We actually do not want to import `CFNetwork` as a image/web framework only if need. This is a bug caused by Apple and fixed in iOS 9, so we just define that symbol inside our framework. If you min-target-deployment version is iOS 8 and want to use `NSURLSessionTaskPriority` symbol as well, you'd better import `CFNetwork`.

**Comment by dreampiggy** [comment] 2018-02-28 04:36
@mzgreat521 @mythodeia 4.3.2 released. You can try pod update or carthage update.

**Closed by dreampiggy** 2018-02-28 04:36 UTC
Labels: crash

**Comment by mzgreat521** [comment] 2018-03-03 02:38
@dreampiggy OK. Thank you!

**Comment by michaelmou** [comment] 2019-09-04 10:41
how about the macos10.10....

**Comment by michaelmou** [comment] 2019-09-04 10:51
i'm looking the code :
#if (__IPHONE_OS_VERSION_MIN_REQUIRED && __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_9_0)
const float NSURLSessionTaskPriorityHigh = 0.75;
const float NSURLSessionTaskPriorityDefault = 0.5;
const float NSURLSessionTaskPriorityLow = 0.25;
#endif
but ,macos not work ..help..

**Comment by dreampiggy** [comment] 2019-09-04 11:11
> how about the macos10.10....

? What issue you're talking about ? You means that macOS 10.10 has no symbol of that `NSURLSessionTaskPriorityHigh`?

If so, fire another new issue, and maybe I need a virtual machine (I don't have any macOS 10.10 device) to reproduce this and fix this.

**Comment by dreampiggy** [comment] 2019-09-04 11:12
The Apple's documentation still shows it's macOS 10.10 + API. Good Apple :)

https://developer.apple.com/documentation/foundation/nsurlsessiontaskpriorityhigh?language=objc
