### ISSUE TITLE
How to use this SDK with Swift?

### ISSUE THREAD

**Issue by harshcs** [rs/SDWebImage#993] opened 2014-12-22 06:05 UTC
Hi,
I am working on Swift based project and I have to download and upload images in that app. I have already used your SDK with Objective C and it worked great! But now I want to use your SDK with Swift language but you haben't mentioned the steps on how to use this SDK with Swift. Please help me in that regard as I have mentioned my query on Stackoverflow but I didn't get any help from there!

**Comment by klundberg** [comment] 2015-01-20 22:19
I havent done it but you should just be able to `#import <SDWebImage/SDWebImage.h>` in your bridging header that is generated if you have a mixed swift/objc-c project. if it's a pure swift project you need to add that header yourself (which i don't know how to do myself, but you can force xcode to do it for you if you add an obj-c file and throw that file away afterwards).

**Comment by thedamfr** [comment] 2015-01-21 13:45
Cocoapods support Swift.

Import via Cocoapods.

import SDWebImage in your swift sheet.

look for sd_* methods on UIImageView!

**Comment by chenenyu** [comment] 2015-03-02 06:15
How to resolve this issue?

**Comment by alexdd55** [comment] 2015-03-07 17:37
[This might help]
(http://www.thelittlebakery.org/2015/02/objective-c-swift-projects-bridging-header/)

**Comment by bpoplauschi** [comment] 2015-03-19 12:17
We need to add a Swift section in our Readme.md file, explaining how to get SDWebImage working with Swift.

**Comment by alexdd55** [comment] 2015-03-19 13:13
a list with all available functions would be nice, too.

**Comment by basememara** [comment] 2015-05-30 11:43
The problem is that extensions don't work with Swift frameworks yet. Several CocoaPods are suffering from this :(((

http://stackoverflow.com/questions/24175596/swift-framework-does-not-include-symbols-from-extensions-to-generic-structs

Please make some noise in the Apple forums and feedback.

**Comment by adrianmacneil** [comment] 2015-09-11 19:18
Here's how I got it working (using CocoaPods and dynamic frameworks, no messy bridging headers):

Podfile:

    platform :ios, '8.0'
    use_frameworks!

    target 'MyApp' do
      pod 'SDWebImage'
    end

Run `pod install`. Then, at the top of your source file add:

    import SDWebImage

Now it's ready to use!

    cell.imageView.sd_setImageWithURL(myUrl)

**Comment by mythodeia** [comment] 2015-09-12 06:36
closing this based on comments above. thanks @adrianmacneil

**Closed by mythodeia** 2015-09-12 06:36 UTC

**Comment by rsahu34** [comment] 2016-07-20 16:11
Hi @amacneil  ,

i have installed the pod file, but there is no "SDWebImage" file , when i am trying to import "import SDWebImage" i am getting error
