### ISSUE TITLE
Methods （cancelInternal／dealloc／reset） crash on  V4.0

### ISSUE THREAD

**Issue by Cooriyou** [rs/SDWebImage#1925] opened 2017-06-02 16:19 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 8.0 Later
 SDWebImage Version      | 4.0.0
 Integration Method      | manually
 Xcode Version           | Xcode 8.3.2
 Repro rate              |  sometimes 0.08%
 Repro with our demo prj | does it happen with our demo project?
 Demo project link       | null

### Issue Description and Steps

1.  -[SDWebImageDownloaderOperation cancelInternal]_block_invoke (SDWebImageDownloaderOperation.m:205)   

2.[UIView(WebCache) sd_internalSetImageWithURL:placeholderImage:options:operationKey:setImageBlock:progress:completed:] (UIView+WebCache.m:39)

3.[SDWebImageDownloaderOperation dealloc] (SDWebImageDownloaderOperation.m:83)

4.[SDWebImageDownloaderOperation reset]_block_invoke (SDWebImageDownloaderOperation.m:225)

Crash on V4.0.0 More than V3.7.6 version ，I need help ，how to fix them. so much crashed

**Comment by skyline75489** [comment] 2017-06-03 23:49
I believe this is a duplicate of #1883 ?

**Comment by Cooriyou** [comment] 2017-06-05 02:02
@skyline75489 how to  fix it ？

**Comment by skyline75489** [comment] 2017-06-05 02:03
Try #1858 and see if it works

**Comment by Cooriyou** [comment] 2017-06-06 03:33
I use  #1858 try to fixed it ， better than last version， but there is still a crash ，different error。

you can try used UITableView have 100+ cells to show web image ， move up and down quickly ，will crashed

<img width="1440" alt="screen shot 2017-06-06 at 11 24 14 am" src="https://cloud.githubusercontent.com/assets/16461292/26812670/a6f7a348-4aab-11e7-946e-115cf1f13edc.png">

**Comment by joshuafeldman** [comment] 2017-06-07 21:38
👀

**Comment by bpoplauschi** [comment] 2017-07-28 18:00
Should be fixed by #1940 - closing for now

**Closed by bpoplauschi** 2017-07-28 18:00 UTC
