### ISSUE TITLE
SDWebImage somehow returning responses to AFNetworking HTTP requests

### ISSUE THREAD

**Issue by enwar3** [rs/SDWebImage#1399] opened 2015-12-14 21:36 UTC
Really perplexing bug we have.

We're using AFNetworking and Overcoat to make HTTP requests that expect a JSON object back and we're using SDWebImage to prefetch some images. But the strange thing is, sometimes the response that AFNetworking gets is the image that SDWebImage is prefetching.

How is this possible? I assumed that SDWebImage and AFNetworking wouldn't share state.

However, we do use the SDWebImageRefreshCached prefetcher option, which I notice used NSURLCache (maybe conflicts with AFNetworking)?

**Comment by bpoplauschi** [comment] 2016-05-29 19:52
Wow, this is indeed very strange. Did you find the cause? I am going to close the issue. If the issue still exists, you might get more help on StackOverflow.

**Closed by bpoplauschi** 2016-05-29 19:52 UTC

**Comment by hoalby** [comment] 2016-06-01 07:04
NSURLCache?

**Comment by mberube09** [comment] 2016-07-20 14:31
I am currently experiencing the exact same problem. I am stuck using AFNetwork 1.X due to RestKit dependency. Does anyone have an idea where I could start digging? I'm having a hard time reproducing it locally but I see in the logs that some of my clients are experiencing the problem.

**Comment by enwar3** [comment] 2016-07-20 17:37
Whoa it's been a while!

@mberube09 we tried a few things at the time to try and fix it, I think the main fix for us was to turn off the `SDWebImageRefreshCached` option because it was using NSURLCache, which might've shared state with AFNetworking. We also switched our API class to a singleton pattern.

I remember this was really frustrating/perplexing, I hope you figure it out! 😀 Would love to hear how you fix it!

**Comment by mberube09** [comment] 2016-07-21 12:20
Well I discovered that in release 3.8.x, SDWebImage switched from using NSURLConnection to NSURLSession, which seems to have fixed the issue. I was able to reproduce my problem fairly often by automating some task inside my app and letting it run for a few minutes. After upgrading to 3.8.x, I let it go for almost an hour without any issue. I considered it case closed! 💃

**Comment by enwar3** [comment] 2016-07-21 17:49
Woo hoo!! 🎉🙌

**Comment by bpoplauschi** [comment] 2016-08-26 20:24
Great to hear this.
