### ISSUE TITLE
Dead lock

### ISSUE THREAD

**Issue by cherpake** [rs/SDWebImage#507] opened 2013-09-22 21:20 UTC
Dead lock when using - (BOOL)diskImageExistsForURL:(NSURL *)url; to check if image exists on the disc.

As it's calling: 

- (BOOL)diskImageExistsWithKey:(NSString *)key
{
    __block BOOL exists = NO;
//
// DEAD LOCK HERE
//
    dispatch_sync(_ioQueue, ^ 
    {
        exists = [_fileManager fileExistsAtPath:[self defaultCachePathForKey:key]];
    });
    
    return exists;
}

and another thread is waiting on:

            dispatch_main_sync_safe(^
            {
                doneBlock(diskImage, SDImageCacheTypeDisk);
            });

in this method: - (NSOperation *)queryDiskCacheForKey:(NSString *)key done:(void (^)(UIImage *image, SDImageCacheType cacheType))doneBlock;

**Comment by nicksnyder** [comment] 2015-04-28 21:00
I can reliably reproduce this problem using SDWebImage 3.7.2, Xcode 6.2, in the iPhone 6 iOS 8.2 simulator.

See this project:
https://github.com/nicksnyder/iOS-UIWebView-vs-UITableView

**Comment by mythodeia** [comment] 2015-04-29 06:00
@nicksnyder you produce the deadlock by setting the maxConcurrentDownloads to 1024. This sets the ```maxConcurrentOperationCount``` of the ```NSOperationQueue``` to 1024 so NSOperationQueue will try to execute at the same time 1024 operations. This will surely hurt the system.
I tried it with as less as 70 in my system and still it deadlocks. 60 is the magic number for me to make it work

**Comment by nicksnyder** [comment] 2015-04-29 06:32
I didn't mean to imply that 1024 was the smallest number needed to deadlock, but it does seem to vary based on the hardware being run on (which is why I put a silly high number in the bug report).

32 concurrent operations performs better than 3 (the default) in my project. I was manually searching for the sweet spot which is when I reproduced the deadlock. The deadlock is indeed still a bug with SDWebImage, right?

**Comment by mythodeia** [comment] 2015-04-29 07:15
i think that the deadlock in SDWebImage occurs because of race conditions when requests are cancelled or finished. NSOperationQueue does not dequeue an operation until its finished state changes to true. So there might be some issues there.

**Comment by bpoplauschi** [comment] 2016-09-30 12:29
Should be fixed by the latest 4.x branch changes (Redone the stuff from #781 by 062e50a f7e8246 c77adf4 265ace4 0c47bc3. Same stuff: replaced all sync calls to the completion with async, cleaned up the code a bit).

**Closed by bpoplauschi** 2016-09-30 12:29 UTC
Labels: bug
