### ISSUE TITLE
Starting a prefetch cancels all running operations, even ones initiated by sd_setImageWithURL:

### ISSUE THREAD

**Issue by gjritter** [rs/SDWebImage#1030] opened 2015-02-02 22:28 UTC
If I use the SDWebImagePrefetcher to prefetchURLs: while some downloads initiated by sd_setImageWithURL: are happening, the prefetch cancels those downloads. Is there some way to prevent this behaviour, or is it expected and we should work around it by avoiding the use of the prefetcher and sd_setImageWithURL: at the same time?

**Comment by mythodeia** [comment] 2015-02-03 06:47
as far as i can see the prefetcher calls ```cancelPrefetching``` before starting to prevent duplicate requests. This method will call the ```[self.manager cancelAll]``` which in turn cancels all running operations by design. 
Can you try initiating the prefetcher using this:
```
SDWebImagePrefetcher *prefetcher = [[SDWebImagePrefetcher alloc] init];
````
instead of using the ```sharedImagePrefetcher```

This will create a new instance of ```SDWebImageManager``` instead of using the global one.

**Comment by timkoma** [comment] 2015-02-08 20:07
SDWebImagePrefetcher and UIImageView both use [SDWebImageDownloader sharedDownloader] or better to say SDWebImageManager instances share download manager. So cancelPrefetching can cause this happen, see #1034

**Comment by gjritter** [comment] 2015-02-09 23:22
Thanks @mythodeia and @timkoma - I went ahead and created a new prefetcher for situations like this to prevent the shared prefetcher from cancelling the operations started by UIImageView+WebCache.

**Comment by mythodeia** [comment] 2015-02-10 06:42
glad we helped! closing this

**Closed by mythodeia** 2015-02-10 06:42 UTC

**Comment by cherpake** [comment] 2015-03-04 15:24
even when not using sharedImagePrefetcher and creating another one like @timkoma,
its still happening - i can't figure why, but disabling perfecting solves the issue of images not being loaded.

**Comment by inPhilly** [comment] 2020-03-28 18:39
Can anyone comment on what is the best current practice to prefetch images for a UITableView or UICollectionView? It is not immediately obvious upon reading these answers.

**Comment by dreampiggy** [comment] 2020-03-28 18:45
This is the old behavior in SD 4.x. Already been fixed ipdue to massive user requests.

In 5.x, each Prefetcher give you a token, your cancel only effected the prefetched one, not effect others fetching url.

See behavior changes in 5.c migration guide: https://github.com/SDWebImage/SDWebImage/wiki/5.0-Migration-guide
